import { CalendarDays, Clock3, CreditCard, Mail, MapPin, Phone, UserRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Badge, Button, Drawer } from '@/components/common';
import { managementMoney } from '@/data/managementData';
import type { ManagementBooking } from '@/types/management';

export const bookingStatus = { pending: { label: 'Chờ xác nhận', variant: 'warning' }, confirmed: { label: 'Đã xác nhận', variant: 'success' }, playing: { label: 'Đang chơi', variant: 'info' }, completed: { label: 'Hoàn thành', variant: 'neutral' }, cancelled: { label: 'Đã hủy', variant: 'danger' } } as const;
export const paymentStatus = { paid: { label: 'Đã thanh toán', variant: 'success' }, partial: { label: 'Đã đặt cọc', variant: 'info' }, unpaid: { label: 'Chưa thanh toán', variant: 'warning' }, refunded: { label: 'Đã hoàn tiền', variant: 'neutral' } } as const;

export function ManagementBookingDrawer({ booking, onClose, onConfirm, onCancel }: { booking?: ManagementBooking; onClose: () => void; onConfirm?: (booking: ManagementBooking) => void; onCancel?: (booking: ManagementBooking) => void }) {
  if (!booking) return null; const status = bookingStatus[booking.status]; const payment = paymentStatus[booking.payment];
  return <Drawer open title={`Booking ${booking.id}`} onClose={onClose}><div className="flex flex-wrap gap-2"><Badge variant={status.variant}>{status.label}</Badge><Badge variant={payment.variant}>{payment.label}</Badge><Badge>{booking.source}</Badge></div><div className="mt-5 rounded-xl bg-slate-50 p-4"><h3 className="font-bold">{booking.venue}</h3><p className="mt-1 flex gap-2 text-sm text-slate-500"><MapPin size={16} />{booking.court} · {booking.sport}</p><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><p><CalendarDays size={15} className="mb-1 text-brand-600" /><span className="block text-xs text-slate-400">Ngày chơi</span><b>{booking.date.split('-').reverse().join('/')}</b></p><p><Clock3 size={15} className="mb-1 text-brand-600" /><span className="block text-xs text-slate-400">Khung giờ</span><b>{booking.startTime}–{booking.endTime}</b></p></div></div><div className="mt-5 space-y-3 text-sm"><h3 className="font-bold">Thông tin khách hàng</h3><p className="flex gap-2"><UserRound size={17} className="text-slate-400" />{booking.customer}</p><p className="flex gap-2"><Phone size={17} className="text-slate-400" />{booking.phone}</p><p className="flex gap-2"><Mail size={17} className="text-slate-400" />{booking.email}</p></div><div className="mt-5 rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between text-sm"><span className="flex gap-2 text-slate-500"><CreditCard size={17} />Tổng thanh toán</span><b className="text-lg text-brand-700">{managementMoney(booking.total)}</b></div>{booking.note && <p className="mt-3 border-t border-slate-100 pt-3 text-xs text-slate-500">Ghi chú: {booking.note}</p>}</div><div className="mt-6 grid gap-2">{booking.status === 'pending' && onConfirm && <Button onClick={() => onConfirm(booking)}>Xác nhận booking</Button>}{booking.status !== 'cancelled' && booking.status !== 'completed' && onCancel && <Button variant="danger" onClick={() => onCancel(booking)}>Hủy booking</Button>}<Link to={`/management/bookings/${booking.id}`}><Button variant="outline" className="w-full">Xem trang chi tiết</Button></Link></div></Drawer>;
}
