import { CalendarDays, CheckCircle2, Clock3, ShieldCheck } from 'lucide-react';
import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import type { Venue } from '@/types/index';
import { Button, Input, Select, useToast } from '@/components/common';

export function VenueBookingPanel({ venue }: { venue: Venue }) {
  const { toast } = useToast(); const navigate = useNavigate(); const [date, setDate] = useState(''); const [courtId, setCourtId] = useState(venue.courts[0]?.id ?? ''); const [slot, setSlot] = useState('');
  const court = useMemo(() => venue.courts.find((item) => item.id === courtId), [venue.courts, courtId]); const price = court?.price ?? venue.price;
  const continueBooking = () => { if (!date || !courtId || !slot) { toast('Vui lòng chọn đầy đủ ngày, sân và khung giờ.', 'error'); return; } sessionStorage.setItem('sporthub_booking_prefill', JSON.stringify({ date, courtId, slot })); navigate(`/booking/${venue.id}`); };
  return <aside className="rounded-card border border-slate-200 bg-white p-5 shadow-card lg:sticky lg:top-20"><div className="flex items-end justify-between border-b border-slate-100 pb-4"><div><span className="text-xs text-slate-500">Giá sân từ</span><p><b className="text-2xl text-brand-700">{price.toLocaleString('vi-VN')}đ</b><span className="text-xs text-slate-500"> / giờ</span></p></div><span className="flex items-center gap-1 text-xs font-semibold text-brand-700"><CheckCircle2 size={15} />Còn lịch</span></div><div className="mt-5 space-y-4"><Input label="Chọn ngày" type="date" min={new Date().toISOString().slice(0, 10)} value={date} onChange={(e) => setDate(e.target.value)} leftIcon={<CalendarDays size={17} />} disabled={!venue.available} /><Select label="Chọn sân" value={courtId} onChange={(e) => { setCourtId(e.target.value); setSlot(''); }} options={venue.courts.map((item) => ({ label: `${item.name} · ${item.price.toLocaleString('vi-VN')}đ`, value: item.id }))} disabled={!venue.available} /><fieldset><legend className="mb-2 flex items-center gap-2 text-sm font-medium text-slate-700"><Clock3 size={16} />Chọn khung giờ</legend><div className="grid grid-cols-3 gap-2">{court?.availableSlots.length ? court.availableSlots.map((item) => <button type="button" key={item} onClick={() => setSlot(item)} className={`rounded-lg border px-2 py-2 text-xs font-semibold ${slot === item ? 'border-brand-600 bg-brand-50 text-brand-700 ring-2 ring-brand-100' : 'border-slate-200 text-slate-600 hover:border-brand-400'}`}>{item}</button>) : <p className="col-span-3 rounded-lg bg-slate-50 p-3 text-xs text-slate-500">Sân này chưa có lịch trống.</p>}</div></fieldset></div><div className="mt-5 border-t border-slate-100 pt-4 text-sm"><div className="flex justify-between text-slate-500"><span>Tiền sân dự kiến</span><span>{price.toLocaleString('vi-VN')}đ</span></div><div className="mt-3 flex justify-between font-bold"><span>Tổng cộng</span><span>{price.toLocaleString('vi-VN')}đ</span></div></div><Button onClick={continueBooking} disabled={!venue.available} size="lg" className="mt-5 w-full">{venue.available ? 'Tiếp tục đặt sân' : 'Tạm ngưng nhận đặt'}</Button><p className="mt-3 flex items-center justify-center gap-1.5 text-xs text-slate-500"><ShieldCheck size={14} />Bạn chưa bị tính phí ở bước này</p></aside>;
}
