import { CalendarDays, RefreshCw, TrendingDown, TrendingUp } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Badge, Button, EmptyState, Input, LoadingSkeleton, PageHeader, useToast } from '@/components/common';
import { apiRequest } from '@/services/apiClient';

interface Summary { date_from: string; date_to: string; booking_value: number; collected_amount: number; deposit_amount: number; held_deposit_amount: number; outstanding_amount: number; completed_revenue: number; refunded_amount: number; net_revenue: number; court_revenue: number; service_revenue: number; total_revenue: number; completed_bookings: number; cancelled_bookings: number; previous_net_revenue: number; change_percent: number | null; today_revenue: number; week_revenue: number; month_revenue: number; }
interface Breakdown { key: string; label: string; booking_count: number; collected_amount: number; refunded_amount: number; net_revenue: number; }
interface Transaction { booking_id: number; booking_code: string; customer_name: string; facility_name: string; field_name: string; sport_type: string; booking_date: string; court_amount: number; service_amount: number; total_amount: number; collected_amount: number; refunded_amount: number; net_revenue: number; outstanding_amount: number; status: string; last_paid_at: string | null; }
interface ProductUsage { product_id: number; name: string; product_type: 'SELL' | 'RENT' | 'SERVICE'; quantity: number; booking_count: number; revenue: number; }
interface Report { summary: Summary; granularity: string; trend: Breakdown[]; by_facility: Breakdown[]; by_field: Breakdown[]; by_sport: Breakdown[]; by_time_slot: Breakdown[]; popular_products: ProductUsage[]; transactions: Transaction[]; }
type Preset = 'today' | '7days' | '30days' | 'month' | 'previous_month' | 'custom';
const money = (value: number) => new Intl.NumberFormat('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }).format(value);
const iso = (value: Date) => `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`;
const statusLabels: Record<string, string> = { pending_payment: 'Chờ thanh toán', pending_confirmation: 'Chờ xác nhận', confirmed: 'Đã xác nhận', in_progress: 'Đang sử dụng', completed: 'Hoàn thành', cancelled: 'Đã hủy', cancelled_by_customer: 'Khách hủy', cancelled_by_owner: 'Chủ sân hủy', expired: 'Hết hạn', no_show: 'Khách vắng mặt', failed: 'Thất bại', rejected: 'Từ chối' };

function rangeFor(preset: Preset) {
  const today = new Date(); let start = new Date(today); let end = new Date(today);
  if (preset === '7days') start.setDate(today.getDate() - 6);
  if (preset === '30days') start.setDate(today.getDate() - 29);
  if (preset === 'month') start = new Date(today.getFullYear(), today.getMonth(), 1);
  if (preset === 'previous_month') { start = new Date(today.getFullYear(), today.getMonth() - 1, 1); end = new Date(today.getFullYear(), today.getMonth(), 0); }
  return { from: iso(start), to: iso(end) };
}

export function ManagementRevenuePage() {
  const [preset, setPreset] = useState<Preset>('30days');
  const initial = rangeFor('30days'); const [from, setFrom] = useState(initial.from); const [to, setTo] = useState(initial.to);
  const [report, setReport] = useState<Report>(); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false);
  const { toast } = useToast();
  const load = () => {
    setLoading(true); setFailed(false);
    apiRequest<Report>(`/dashboard/revenue-analytics?date_from=${from}&date_to=${to}`).then(setReport).catch((error) => { setFailed(true); toast(error instanceof Error ? error.message : 'Không tải được thống kê doanh thu.', 'error'); }).finally(() => setLoading(false));
  };
  useEffect(load, [from, to]);
  const choose = (value: Preset) => { setPreset(value); if (value !== 'custom') { const next = rangeFor(value); setFrom(next.from); setTo(next.to); } };
  const top = useMemo(() => report ? [...report.by_field].sort((a, b) => b.net_revenue - a.net_revenue) : [], [report]);
  if (loading && !report) return <LoadingSkeleton lines={12} />;
  if (failed && !report) return <EmptyState title="Không tải được báo cáo doanh thu" description="Kiểm tra kết nối hoặc quyền báo cáo rồi thử lại." action={<Button onClick={load}>Thử lại</Button>} />;
  if (!report) return null;
  const { summary } = report;
  return <><PageHeader title="Thống kê doanh thu" description={`Số liệu Booking–Payment–Refund từ ${new Date(`${from}T00:00`).toLocaleDateString('vi-VN')} đến ${new Date(`${to}T00:00`).toLocaleDateString('vi-VN')}.`} actions={<Button variant="outline" loading={loading} leftIcon={<RefreshCw size={16} />} onClick={load}>Làm mới</Button>} />
    <section className="mb-5 rounded-card border bg-white p-4"><div className="flex flex-wrap gap-2">{([['today', 'Hôm nay'], ['7days', '7 ngày'], ['30days', '30 ngày'], ['month', 'Tháng này'], ['previous_month', 'Tháng trước'], ['custom', 'Tùy chỉnh']] as [Preset, string][]).map(([value, label]) => <Button key={value} size="sm" variant={preset === value ? 'primary' : 'outline'} onClick={() => choose(value)}>{label}</Button>)}</div>{preset === 'custom' && <div className="mt-4 grid max-w-xl gap-3 sm:grid-cols-2"><Input type="date" label="Từ ngày" value={from} max={to} onChange={(event) => setFrom(event.target.value)} leftIcon={<CalendarDays size={16} />} /><Input type="date" label="Đến ngày" value={to} min={from} onChange={(event) => setTo(event.target.value)} leftIcon={<CalendarDays size={16} />} /></div>}</section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Metric label="Doanh thu hôm nay" value={summary.today_revenue} /><Metric label="Doanh thu tuần này" value={summary.week_revenue} /><Metric label="Doanh thu tháng này" value={summary.month_revenue} /></section>
    <section className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"><Metric label="Doanh thu tiền sân" value={summary.court_revenue} /><Metric label="Doanh thu dịch vụ" value={summary.service_revenue} /><Metric label="Tổng doanh thu" value={summary.total_revenue} highlight /><Metric label="Tổng giá trị booking hợp lệ" value={summary.booking_value} /><Metric label="Tiền thực tế đã thu" value={summary.collected_amount} /><Metric label="Tiền cọc đã thu" value={summary.deposit_amount} /><Metric label="Tiền cọc đang giữ" value={summary.held_deposit_amount} /><Metric label="Còn phải thu" value={summary.outstanding_amount} /><Metric label="Doanh thu hoàn tất" value={summary.completed_revenue} /><Metric label="Đã hoàn cho khách" value={summary.refunded_amount} danger /><Metric label="Doanh thu thực nhận" value={summary.net_revenue} highlight /></section>
    <div className="mt-3 flex flex-wrap items-center gap-4 rounded-card border bg-white p-4 text-sm"><span>Hoàn thành: <b>{summary.completed_bookings} booking</b></span><span>Đã hủy/hết hạn: <b>{summary.cancelled_bookings} booking</b></span><span className={`ml-auto flex items-center gap-1 font-semibold ${summary.change_percent === null ? 'text-slate-500' : summary.change_percent >= 0 ? 'text-emerald-700' : 'text-red-700'}`}>{summary.change_percent === null ? 'Chưa đủ dữ liệu kỳ trước' : <>{summary.change_percent >= 0 ? <TrendingUp size={17} /> : <TrendingDown size={17} />}{Math.abs(summary.change_percent)}% so với kỳ trước</>}</span></div>
    {report.transactions.length ? <div className="mt-6 space-y-6"><RevenueChart title="Doanh thu thực nhận theo thời gian" items={report.trend} /><ProductUsageTable items={report.popular_products} /><div className="grid gap-5 xl:grid-cols-2"><RevenueChart title="Theo cơ sở" items={report.by_facility} /><RevenueChart title="Theo môn thể thao" items={report.by_sport} /></div><div className="grid gap-5 xl:grid-cols-2"><Ranking title="Sân doanh thu cao" items={top.slice(0, 5)} /><Ranking title="Sân doanh thu thấp" items={[...top].reverse().slice(0, 5)} /></div><BreakdownTable title="Doanh thu theo sân" items={report.by_field} /><BreakdownTable title="Booking và doanh thu theo khung giờ" items={report.by_time_slot} /><TransactionTable items={report.transactions} /></div> : <div className="mt-6"><EmptyState title="Chưa có dữ liệu trong kỳ" description="Không có booking hoặc giao dịch thuộc khoảng ngày đã chọn." /></div>}
  </>;
}

function Metric({ label, value, highlight, danger }: { label: string; value: number; highlight?: boolean; danger?: boolean }) { return <article className={`rounded-card border p-4 ${highlight ? 'border-brand-300 bg-brand-50' : 'bg-white'}`}><p className="text-xs font-semibold text-slate-500">{label}</p><b className={`mt-2 block text-xl ${danger ? 'text-red-700' : highlight ? 'text-brand-700' : 'text-slate-900'}`}>{money(value)}</b></article>; }
function RevenueChart({ title, items }: { title: string; items: Breakdown[] }) { return <section className="rounded-card border bg-white p-5"><h2 className="font-bold">{title}</h2>{items.length ? <div className="mt-4 h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={items}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 11 }} /><YAxis tickFormatter={(value) => `${Math.round(Number(value) / 1000)}k`} tick={{ fontSize: 11 }} /><Tooltip formatter={(value) => money(Number(value))} labelFormatter={(label) => String(label)} /><Bar dataKey="net_revenue" name="Doanh thu thực nhận" fill="#059669" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div> : <p className="mt-4 text-sm text-slate-500">Chưa có dữ liệu.</p>}</section>; }
function Ranking({ title, items }: { title: string; items: Breakdown[] }) { return <section className="rounded-card border bg-white p-5"><h2 className="font-bold">{title}</h2><div className="mt-4 space-y-3">{items.length ? items.map((item, index) => <div key={item.key} className="flex items-center gap-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-slate-100 text-xs font-bold">{index + 1}</span><span className="min-w-0 flex-1 truncate text-sm font-medium">{item.label}</span><b className="text-sm text-brand-700">{money(item.net_revenue)}</b></div>) : <p className="text-sm text-slate-500">Chưa có dữ liệu.</p>}</div></section>; }
function BreakdownTable({ title, items }: { title: string; items: Breakdown[] }) { return <section className="overflow-hidden rounded-card border bg-white"><h2 className="border-b p-5 font-bold">{title}</h2><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Nhóm', 'Booking', 'Đã thu', 'Đã hoàn', 'Thực nhận'].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.key} className="border-t"><td className="px-4 py-3 font-semibold">{item.label}</td><td className="px-4 py-3">{item.booking_count}</td><td className="px-4 py-3">{money(item.collected_amount)}</td><td className="px-4 py-3 text-red-700">{money(item.refunded_amount)}</td><td className="px-4 py-3 font-bold text-brand-700">{money(item.net_revenue)}</td></tr>)}</tbody></table></div></section>; }
function ProductUsageTable({ items }: { items: ProductUsage[] }) { return <section className="overflow-hidden rounded-card border bg-white"><h2 className="border-b p-5 font-bold">Sản phẩm & dịch vụ được dùng nhiều</h2><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Sản phẩm / dịch vụ', 'Loại', 'Booking', 'Số lượng', 'Doanh thu snapshot'].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.product_id} className="border-t"><td className="px-4 py-3 font-semibold">{item.name}</td><td className="px-4 py-3">{item.product_type}</td><td className="px-4 py-3">{item.booking_count}</td><td className="px-4 py-3">{item.quantity}</td><td className="px-4 py-3 font-bold text-brand-700">{money(item.revenue)}</td></tr>)}</tbody></table>{!items.length && <p className="p-5 text-sm text-slate-500">Chưa có sản phẩm được sử dụng trong booking hoàn tất.</p>}</div></section>; }
function TransactionTable({ items }: { items: Transaction[] }) { return <section className="overflow-hidden rounded-card border bg-white"><h2 className="border-b p-5 font-bold">Chi tiết booking và giao dịch</h2><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Booking', 'Khách hàng', 'Cơ sở / sân', 'Tổng tiền', 'Đã trả', 'Đã hoàn', 'Thực nhận', 'Còn thu', 'Trạng thái', 'Thanh toán gần nhất'].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={item.booking_id} className="border-t"><td className="px-4 py-3"><b>{item.booking_code}</b><small className="block text-slate-500">{new Date(`${item.booking_date}T00:00`).toLocaleDateString('vi-VN')}</small></td><td className="px-4 py-3">{item.customer_name}</td><td className="px-4 py-3"><b>{item.field_name}</b><small className="block text-slate-500">{item.facility_name} · {item.sport_type}</small></td><td className="px-4 py-3">{money(item.total_amount)}</td><td className="px-4 py-3">{money(item.collected_amount)}</td><td className="px-4 py-3 text-red-700">{money(item.refunded_amount)}</td><td className="px-4 py-3 font-bold text-brand-700">{money(item.net_revenue)}</td><td className="px-4 py-3">{money(item.outstanding_amount)}</td><td className="px-4 py-3"><Badge variant={['completed', 'confirmed'].includes(item.status) ? 'success' : ['cancelled', 'cancelled_by_customer', 'cancelled_by_owner', 'expired', 'failed', 'rejected'].includes(item.status) ? 'danger' : 'warning'}>{statusLabels[item.status] || 'Đã cập nhật'}</Badge></td><td className="px-4 py-3">{item.last_paid_at ? new Date(item.last_paid_at).toLocaleString('vi-VN') : 'Chưa thanh toán'}</td></tr>)}</tbody></table></div></section>; }
