import { AlertTriangle, ArrowRight, ArrowUpRight, CalendarCheck2, CalendarPlus, CircleDollarSign, Clock3, Download, RefreshCw, TrendingDown, TrendingUp, UserPlus, WalletCards, XCircle } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Legend, Line, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Badge, Button, PageHeader, useToast } from '@/components/common';
import { courtPerformance, managementBookings, managementMoney, occupancySeries, revenueSeries, sportSeries } from '@/data/managementData';

const kpis = [
  { label: 'Doanh thu hôm nay', value: '31,6 triệu', change: '+21,1%', good: true, icon: CircleDollarSign, color: 'emerald' },
  { label: 'Doanh thu tháng', value: '154,1 triệu', change: '+15,4%', good: true, icon: WalletCards, color: 'blue' },
  { label: 'Booking hôm nay', value: '24', change: '+4 booking', good: true, icon: CalendarCheck2, color: 'violet' },
  { label: 'Tỷ lệ lấp đầy', value: '76,2%', change: '+5,1%', good: true, icon: TrendingUp, color: 'amber' },
  { label: 'Đang chờ', value: '04', change: 'Cần xử lý', good: false, icon: Clock3, color: 'orange' },
  { label: 'Đã hủy', value: '02', change: '-1 so hôm qua', good: true, icon: XCircle, color: 'rose' },
];
const statusLabel = { pending: 'Chờ xác nhận', confirmed: 'Đã xác nhận', playing: 'Đang chơi', completed: 'Hoàn thành', cancelled: 'Đã hủy' } as const;

export function ManagementDashboardPage() {
  const navigate = useNavigate(); const { toast } = useToast(); const latest = managementBookings.slice(3, 8); const upcoming = managementBookings.filter((item) => item.date === '2026-08-06' && item.status === 'confirmed').slice(0, 3);
  return <><PageHeader title="Tổng quan vận hành" description="Chào buổi sáng, Hoàng! Dữ liệu SportHub Phú Thọ · Cập nhật lúc 11:30, 06/08/2026." actions={<><Button variant="outline" leftIcon={<Download size={16} />} onClick={() => toast('Đã tạo báo cáo tổng quan mẫu.', 'success')}>Xuất báo cáo</Button><Button leftIcon={<CalendarPlus size={16} />} onClick={() => navigate('/management/calendar')}>Tạo booking</Button></>} /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6">{kpis.map((item) => <Kpi key={item.label} {...item} />)}</div>
    <div className="mt-6 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><ChartCard title="Doanh thu theo ngày" subtitle="Đơn vị: triệu đồng · So sánh kỳ trước"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={revenueSeries} margin={{ left: -20, right: 10 }}><defs><linearGradient id="currentRevenue" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#16a05d" stopOpacity={.28} /><stop offset="1" stopColor="#16a05d" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#e2e8f0" strokeDasharray="4 4" /><XAxis dataKey="day" axisLine={false} tickLine={false} tick={{ fontSize: 11 }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11 }} /><Tooltip contentStyle={{ borderRadius: 10, borderColor: '#e2e8f0' }} /><Legend iconType="circle" wrapperStyle={{ fontSize: 12 }} /><Area name="Kỳ này" type="monotone" dataKey="current" stroke="#0d874c" strokeWidth={2.5} fill="url(#currentRevenue)" /><Line name="Kỳ trước" type="monotone" dataKey="previous" stroke="#94a3b8" strokeWidth={2} strokeDasharray="5 5" dot={false} /></AreaChart></ResponsiveContainer></div></ChartCard><ChartCard title="Lượt đặt theo môn" subtitle="Tỷ trọng 428 booking trong tháng"><div className="h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={sportSeries} dataKey="value" nameKey="name" innerRadius={62} outerRadius={92} paddingAngle={3}>{sportSeries.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip formatter={(value) => `${value}%`} /><Legend iconType="circle" wrapperStyle={{ fontSize: 12 }} /></PieChart></ResponsiveContainer></div></ChartCard></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><ChartCard title="Tỷ lệ lấp đầy theo khung giờ" subtitle="Khung 18h–20h đang có nhu cầu cao nhất"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={occupancySeries} margin={{ left: -20 }}><CartesianGrid vertical={false} stroke="#e2e8f0" strokeDasharray="4 4" /><XAxis dataKey="time" axisLine={false} tickLine={false} tick={{ fontSize: 11 }} /><YAxis domain={[0, 100]} axisLine={false} tickLine={false} tick={{ fontSize: 11 }} /><Tooltip formatter={(value) => `${value}%`} cursor={{ fill: '#f1f5f9' }} /><Bar dataKey="rate" name="Lấp đầy" radius={[5, 5, 0, 0]}>{occupancySeries.map((item) => <Cell key={item.time} fill={item.rate >= 80 ? '#f59e0b' : '#16a05d'} />)}</Bar></BarChart></ResponsiveContainer></div></ChartCard><ChartCard title="Sân hoạt động tốt nhất" subtitle="Doanh thu tháng · Đơn vị triệu đồng"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={courtPerformance} layout="vertical" margin={{ left: 8, right: 12 }}><CartesianGrid horizontal={false} stroke="#e2e8f0" strokeDasharray="4 4" /><XAxis type="number" axisLine={false} tickLine={false} tick={{ fontSize: 11 }} /><YAxis type="category" dataKey="court" axisLine={false} tickLine={false} width={58} tick={{ fontSize: 11 }} /><Tooltip contentStyle={{ borderRadius: 10, borderColor: '#e2e8f0' }} /><Bar dataKey="revenue" name="Doanh thu" fill="#2583d8" radius={[0, 5, 5, 0]} /></BarChart></ResponsiveContainer></div></ChartCard></div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><section className="overflow-hidden rounded-card border border-slate-200 bg-white"><SectionHeader title="Booking mới nhất" subtitle="Các yêu cầu vừa được tạo" link="/management/bookings" /><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr><th className="px-5 py-3">Mã</th><th className="px-5 py-3">Khách hàng</th><th className="px-5 py-3">Sân & thời gian</th><th className="px-5 py-3">Tổng tiền</th><th className="px-5 py-3">Trạng thái</th></tr></thead><tbody className="divide-y divide-slate-100">{latest.map((item) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-5 py-3 font-bold text-brand-700">{item.id}</td><td className="px-5 py-3"><b className="block">{item.customer}</b><span className="text-xs text-slate-500">{item.source}</span></td><td className="px-5 py-3"><b>{item.court}</b><span className="block text-xs text-slate-500">{item.date.split('-').reverse().join('/')} · {item.startTime}</span></td><td className="px-5 py-3 font-semibold">{managementMoney(item.total)}</td><td className="px-5 py-3"><Badge variant={item.status === 'pending' ? 'warning' : 'success'}>{statusLabel[item.status]}</Badge></td></tr>)}</tbody></table></div></section><section className="rounded-card border border-slate-200 bg-white"><SectionHeader title="Sắp diễn ra" subtitle="Trong hôm nay" link="/management/calendar" /><div className="divide-y divide-slate-100 px-5">{upcoming.map((item) => <div key={item.id} className="flex gap-3 py-4"><div className="w-14 text-center"><b className="block text-brand-700">{item.startTime}</b><span className="text-[10px] text-slate-400">{item.endTime}</span></div><span className="w-1 rounded-full bg-brand-500" /><div className="min-w-0"><b className="block truncate text-sm">{item.court} · {item.customer}</b><span className="text-xs text-slate-500">{item.id} · {managementMoney(item.total)}</span></div></div>)}</div></section></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-3"><section className="rounded-card border border-amber-200 bg-amber-50/50 p-5"><h2 className="flex items-center gap-2 font-bold text-amber-900"><AlertTriangle size={19} />Cảnh báo vận hành</h2><div className="mt-3 space-y-3 text-sm"><Alert text="Sân A2 bảo trì lúc 12:00–14:00 hôm nay" level="Cần chú ý" /><Alert text="4 booking chờ xác nhận quá 30 phút" level="Cần xử lý" /><Alert text="Tỷ lệ lấp đầy 18h–20h đạt 94%" level="Nhu cầu cao" /></div></section><section className="rounded-card border border-slate-200 bg-white p-5"><h2 className="font-bold">Hoạt động gần đây</h2><div className="mt-3 space-y-4">{['Nguyễn Hoàng xác nhận SH-1086', 'Thu ngân ghi nhận 720.000đ', 'Hệ thống khóa lịch bảo trì Sân A2', 'SH-1091 được hoàn tiền'].map((text, i) => <div key={text} className="flex gap-3 text-sm"><span className="mt-1.5 h-2 w-2 shrink-0 rounded-full bg-brand-500" /><div><p>{text}</p><span className="text-xs text-slate-400">{8 + i * 7} phút trước</span></div></div>)}</div></section><section className="rounded-card border border-slate-200 bg-white p-5"><h2 className="font-bold">Thao tác nhanh</h2><div className="mt-4 grid grid-cols-2 gap-3"><Quick icon={CalendarPlus} text="Tạo booking" onClick={() => navigate('/management/calendar')} /><Quick icon={UserPlus} text="Thêm khách" onClick={() => toast('Đã mở form thêm khách hàng.', 'info')} /><Quick icon={RefreshCw} text="Khóa lịch" onClick={() => navigate('/management/calendar')} /><Quick icon={Download} text="Xuất dữ liệu" onClick={() => toast('Đã xuất dữ liệu mẫu.', 'success')} /></div></section></div>
  </>;
}

function Kpi({ label, value, change, good, icon: Icon, color }: typeof kpis[number]) { const colors: Record<string, string> = { emerald: 'bg-emerald-50 text-emerald-700', blue: 'bg-blue-50 text-blue-700', violet: 'bg-violet-50 text-violet-700', amber: 'bg-amber-50 text-amber-700', orange: 'bg-orange-50 text-orange-700', rose: 'bg-rose-50 text-rose-700' }; return <article className="rounded-card border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between"><span className={`grid h-9 w-9 place-items-center rounded-lg ${colors[color]}`}><Icon size={18} /></span><span className={`flex items-center text-[11px] font-semibold ${good ? 'text-emerald-600' : 'text-amber-600'}`}>{good ? <ArrowUpRight size={13} /> : <Clock3 size={13} />}{change}</span></div><p className="mt-4 text-xs text-slate-500">{label}</p><b className="mt-1 block text-xl text-slate-950">{value}</b></article>; }
function ChartCard({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="rounded-card border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-4"><h2 className="font-bold">{title}</h2><p className="text-xs text-slate-500">{subtitle}</p></div>{children}</section>; }
function SectionHeader({ title, subtitle, link }: { title: string; subtitle: string; link: string }) { return <div className="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 className="font-bold">{title}</h2><p className="text-xs text-slate-500">{subtitle}</p></div><Link to={link} className="flex items-center gap-1 text-xs font-semibold text-brand-700">Xem tất cả <ArrowRight size={14} /></Link></div>; }
function Alert({ text, level }: { text: string; level: string }) { return <div className="rounded-lg border border-amber-200 bg-white p-3"><p className="font-medium text-slate-800">{text}</p><span className="mt-1 block text-[11px] font-semibold text-amber-700">{level}</span></div>; }
function Quick({ icon: Icon, text, onClick }: { icon: typeof CalendarPlus; text: string; onClick: () => void }) { return <button onClick={onClick} className="flex flex-col items-center gap-2 rounded-xl border border-slate-200 p-4 text-xs font-semibold text-slate-700 hover:border-brand-300 hover:bg-brand-50 hover:text-brand-700"><Icon size={20} />{text}</button>; }
