import { useEffect, useState } from 'react';
import { Button, EmptyState, Input, LoadingSkeleton, PageHeader, useToast } from '@/components/common';
import { apiRequest } from '@/services/apiClient';

interface FieldItem { id: number; name: string; }
interface FieldBlock { id: number; field_id: number; field_name: string; block_date: string; start_time: string; end_time: string; reason: string; created_by_name: string; created_at: string; }

export function ManagementFieldBlocksPage() {
  const { toast } = useToast(); const [fields, setFields] = useState<FieldItem[]>([]); const [items, setItems] = useState<FieldBlock[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [fieldId, setFieldId] = useState(''); const [date, setDate] = useState(''); const [start, setStart] = useState('00:00'); const [end, setEnd] = useState('23:59'); const [reason, setReason] = useState('');
  const load = () => Promise.all([apiRequest<{ items: FieldItem[] }>('/fields?page_size=100'), apiRequest<FieldBlock[]>('/field-blocks')]).then(([fieldResult, blocks]) => { setFields(fieldResult.items); setItems(blocks); if (!fieldId && fieldResult.items[0]) setFieldId(String(fieldResult.items[0].id)); });
  useEffect(() => { load().catch((error) => toast(error instanceof Error ? error.message : 'Không tải được lịch khóa.', 'error')).finally(() => setLoading(false)); }, []);
  const create = async () => { if (!fieldId || !date || reason.trim().length < 3) return toast('Chọn sân, ngày và nhập lý do khóa.', 'error'); setBusy(true); try { await apiRequest('/field-blocks', { method: 'POST', body: JSON.stringify({ field_id: Number(fieldId), block_date: date, start_time: start, end_time: end, reason: reason.trim() }) }); setReason(''); await load(); toast('Đã khóa sân trong khoảng thời gian đã chọn.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không thể khóa sân.', 'error'); } finally { setBusy(false); } };
  const remove = async (id: number) => { if (!window.confirm('Mở lại khoảng thời gian này để nhận booking?')) return; try { await apiRequest(`/field-blocks/${id}`, { method: 'DELETE' }); setItems((current) => current.filter((item) => item.id !== id)); toast('Đã mở lại lịch sân.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không thể mở lịch sân.', 'error'); } };
  return <><PageHeader title="Ngày nghỉ và bảo trì" description="Khóa toàn ngày hoặc một khoảng giờ; hệ thống sẽ loại khỏi availability và ngăn booking mới." /><section className="rounded-card border bg-white p-5"><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><label className="text-sm font-medium">Sân<select className="field mt-1" value={fieldId} onChange={(event) => setFieldId(event.target.value)}>{fields.map((field) => <option key={field.id} value={field.id}>{field.name}</option>)}</select></label><Input label="Ngày" type="date" min={new Date().toISOString().slice(0, 10)} value={date} onChange={(event) => setDate(event.target.value)} /><Input label="Từ giờ" type="time" value={start} onChange={(event) => setStart(event.target.value)} /><Input label="Đến giờ" type="time" value={end} onChange={(event) => setEnd(event.target.value)} /><Input label="Lý do *" value={reason} onChange={(event) => setReason(event.target.value)} /></div><Button className="mt-4" loading={busy} onClick={() => void create()}>Tạo lịch khóa</Button></section>{loading ? <LoadingSkeleton lines={6} /> : items.length ? <div className="mt-5 overflow-x-auto rounded-card border bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Sân','Ngày','Khoảng giờ','Lý do','Người tạo',''].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr className="border-t" key={item.id}><td className="px-4 py-3 font-semibold">{item.field_name}</td><td className="px-4 py-3">{item.block_date}</td><td className="px-4 py-3">{item.start_time.slice(0,5)}–{item.end_time.slice(0,5)}</td><td className="px-4 py-3">{item.reason}</td><td className="px-4 py-3">{item.created_by_name}</td><td className="px-4 py-3"><Button size="sm" variant="danger" onClick={() => void remove(item.id)}>Mở lịch</Button></td></tr>)}</tbody></table></div> : <div className="mt-5"><EmptyState title="Chưa có lịch khóa" description="Tất cả sân đang nhận lịch theo khung giờ hoạt động." /></div>}</>;
}
