import { CalendarDays, ChevronLeft, ChevronRight, Filter, List, LockKeyhole, Plus, Rows3 } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Badge, Button, Modal, PageHeader, useToast } from '@/components/common';
import { ManagementBookingDrawer, bookingStatus } from '@/components/management/ManagementBookingDrawer';
import { lockedSlots, managementBookings, ownerCourts } from '@/data/managementData';
import type { ManagementBooking, ManagementBookingStatus } from '@/types/management';

type View = 'day' | 'week' | 'list';
const hours = Array.from({ length: 17 }, (_, i) => `${String(i + 6).padStart(2, '0')}:00`);
const statusColors: Record<ManagementBookingStatus, string> = { pending: 'border-amber-300 bg-amber-50 text-amber-800', confirmed: 'border-emerald-300 bg-emerald-50 text-emerald-800', playing: 'border-blue-300 bg-blue-50 text-blue-800', completed: 'border-slate-300 bg-slate-100 text-slate-600', cancelled: 'border-red-200 bg-red-50 text-red-600' };

export function ManagementCalendarPage() {
  const { toast } = useToast(); const [view, setView] = useState<View>('day'); const [date, setDate] = useState('2026-08-06'); const [bookings, setBookings] = useState(managementBookings); const [selected, setSelected] = useState<ManagementBooking>(); const [slot, setSlot] = useState<{ courtId: string; time: string }>(); const [courtFilter, setCourtFilter] = useState('all'); const [sportFilter, setSportFilter] = useState('all'); const [statusFilter, setStatusFilter] = useState('all'); const [customer, setCustomer] = useState('');
  const visibleCourts = ownerCourts.filter((court) => courtFilter === 'all' || court.id === courtFilter).filter((court) => sportFilter === 'all' || court.sport === sportFilter);
  const dayBookings = bookings.filter((item) => item.date === date && (statusFilter === 'all' || item.status === statusFilter) && visibleCourts.some((court) => court.id === item.courtId));
  const changeDate = (amount: number) => { const next = new Date(`${date}T00:00:00`); next.setDate(next.getDate() + amount); setDate(next.toISOString().slice(0, 10)); };
  const weekDates = useMemo(() => Array.from({ length: 7 }, (_, i) => { const day = new Date(`${date}T00:00:00`); day.setDate(day.getDate() - day.getDay() + 1 + i); return day.toISOString().slice(0, 10); }), [date]);
  const createManual = () => { if (!slot || customer.trim().length < 2) { toast('Vui lòng nhập tên khách hàng.', 'error'); return; } const toMinutes = (time: string) => Number(time.slice(0, 2)) * 60 + Number(time.slice(3, 5)); const start = toMinutes(slot.time); const end = start + 60; const conflict = bookings.some((item) => item.courtId === slot.courtId && item.date === date && ['pending', 'confirmed', 'playing'].includes(item.status) && start < toMinutes(item.endTime) && end > toMinutes(item.startTime)); if (conflict) { toast('Khung giờ này vừa được người khác đặt. Vui lòng chọn thời gian khác.', 'error'); return; } const court = ownerCourts.find((item) => item.id === slot.courtId)!; const nextHour = `${String(Math.floor(end / 60)).padStart(2, '0')}:${String(end % 60).padStart(2, '0')}`; const booking: ManagementBooking = { id: `SH-${1100 + bookings.length}`, customer: customer.trim(), phone: '0900 000 000', email: 'booking@counter.local', venue: 'SportHub Phú Thọ', court: court.name, courtId: court.id, sport: 'Bóng đá', date, startTime: slot.time, endTime: nextHour, total: court.id === 'b1' ? 780000 : court.id === 'a2' ? 480000 : 450000, payment: 'unpaid', status: 'pending', source: 'Tại quầy', createdAt: new Date().toISOString() }; setBookings([booking, ...bookings]); setSlot(undefined); setCustomer(''); toast('Đã tạo booking thủ công.', 'success'); };
  const isLocked = (courtId: string, time: string, targetDate = date) => lockedSlots.find((item) => item.courtId === courtId && item.date === targetDate && time >= item.startTime && time < item.endTime);
  return <><PageHeader title="Lịch quản lý sân" description="Theo dõi tình trạng sân và điều phối booking theo thời gian thực." actions={<Button leftIcon={<Plus size={16} />} onClick={() => setSlot({ courtId: visibleCourts[0]?.id ?? 'a1', time: '10:00' })}>Tạo booking</Button>} /><section className="rounded-card border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-slate-100 p-4 xl:flex-row xl:items-center"><div className="flex items-center gap-2"><Button size="sm" variant="outline" onClick={() => changeDate(view === 'week' ? -7 : -1)}><ChevronLeft size={16} /></Button><Button size="sm" variant="outline" onClick={() => setDate('2026-08-06')}>Hôm nay</Button><Button size="sm" variant="outline" onClick={() => changeDate(view === 'week' ? 7 : 1)}><ChevronRight size={16} /></Button><b className="ml-2 text-sm">{new Date(`${date}T00:00:00`).toLocaleDateString('vi-VN', { weekday: 'long', day: '2-digit', month: '2-digit', year: 'numeric' })}</b></div><div className="flex flex-1 flex-wrap gap-2 xl:justify-end"><select className="field h-9 w-auto min-w-32 text-xs" value={courtFilter} onChange={(e) => setCourtFilter(e.target.value)}><option value="all">Tất cả sân</option>{ownerCourts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="field h-9 w-auto min-w-32 text-xs" value={sportFilter} onChange={(e) => setSportFilter(e.target.value)}><option value="all">Tất cả môn</option><option>Bóng đá</option><option>Cầu lông</option><option>Pickleball</option></select><select className="field h-9 w-auto min-w-36 text-xs" value={statusFilter} onChange={(e) => setStatusFilter(e.target.value)}><option value="all">Tất cả trạng thái</option><option value="pending">Chờ xác nhận</option><option value="confirmed">Đã xác nhận</option><option value="completed">Hoàn thành</option><option value="cancelled">Đã hủy</option></select><div className="flex rounded-lg bg-slate-100 p-1">{([['day', CalendarDays, 'Ngày'], ['week', Rows3, 'Tuần'], ['list', List, 'Danh sách']] as const).map(([value, Icon, label]) => <button key={value} onClick={() => setView(value)} className={`flex items-center gap-1 rounded-md px-2.5 py-1.5 text-xs font-semibold ${view === value ? 'bg-white text-brand-700 shadow-sm' : 'text-slate-500'}`}><Icon size={14} />{label}</button>)}</div></div></div>
      {view === 'day' && <DayView courts={visibleCourts} bookings={dayBookings} date={date} locked={isLocked} onBooking={setSelected} onSlot={(courtId, time) => setSlot({ courtId, time })} />}
      {view === 'week' && <WeekView dates={weekDates} bookings={bookings.filter((item) => statusFilter === 'all' || item.status === statusFilter)} onBooking={setSelected} />}
      {view === 'list' && <ListView bookings={dayBookings} onBooking={setSelected} />}
      <div className="flex flex-wrap gap-4 border-t border-slate-100 p-4 text-xs text-slate-500"><Legend color="bg-emerald-100 border-emerald-300" text="Đã xác nhận" /><Legend color="bg-amber-100 border-amber-300" text="Chờ xác nhận" /><Legend color="bg-slate-200 border-slate-300" text="Đã hoàn thành" /><Legend color="bg-slate-300" text="Khung giờ bị khóa" /><Legend color="bg-white border-slate-200" text="Khung giờ trống" /></div></section>
    <ManagementBookingDrawer booking={selected} onClose={() => setSelected(undefined)} onConfirm={(item) => { setBookings(bookings.map((entry) => entry.id === item.id ? { ...entry, status: 'confirmed' } : entry)); setSelected(undefined); toast('Đã xác nhận booking.', 'success'); }} onCancel={(item) => { setBookings(bookings.map((entry) => entry.id === item.id ? { ...entry, status: 'cancelled' } : entry)); setSelected(undefined); toast('Đã hủy booking.', 'success'); }} />
    <Modal open={Boolean(slot)} onClose={() => setSlot(undefined)} title="Tạo booking thủ công" description={`${ownerCourts.find((item) => item.id === slot?.courtId)?.name ?? ''} · ${date.split('-').reverse().join('/')} · ${slot?.time ?? ''}`}><div className="space-y-4"><label className="block text-sm font-medium">Khách hàng *<input autoFocus className="field mt-1.5" placeholder="Nhập họ tên khách" value={customer} onChange={(e) => setCustomer(e.target.value)} /></label><label className="block text-sm font-medium">Sân<select className="field mt-1.5" value={slot?.courtId} onChange={(e) => slot && setSlot({ ...slot, courtId: e.target.value })}>{ownerCourts.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Bắt đầu<input className="field mt-1.5" type="time" value={slot?.time} onChange={(e) => slot && setSlot({ ...slot, time: e.target.value })} /></label><label className="text-sm font-medium">Nguồn<select className="field mt-1.5"><option>Tại quầy</option><option>Điện thoại</option></select></label></div><div className="flex justify-end gap-2 pt-2"><Button variant="ghost" onClick={() => setSlot(undefined)}>Hủy</Button><Button onClick={createManual}>Tạo booking</Button></div></div></Modal></>;
}

function DayView({ courts, bookings, date, locked, onBooking, onSlot }: { courts: typeof ownerCourts; bookings: ManagementBooking[]; date: string; locked: (court: string, time: string, date?: string) => typeof lockedSlots[number] | undefined; onBooking: (booking: ManagementBooking) => void; onSlot: (court: string, time: string) => void }) { return <div className="overflow-x-auto"><div className="min-w-[760px]"><div className="grid border-b border-slate-200 bg-slate-50" style={{ gridTemplateColumns: `72px repeat(${courts.length}, minmax(210px, 1fr))` }}><div className="p-3 text-xs font-semibold text-slate-400">Giờ</div>{courts.map((court) => <div key={court.id} className="border-l border-slate-200 p-3 text-center"><b className="text-sm">{court.name}</b><span className="ml-2 text-xs text-slate-400">{court.sport}</span></div>)}</div>{hours.map((time) => <div key={time} className="grid min-h-[70px] border-b border-slate-100" style={{ gridTemplateColumns: `72px repeat(${courts.length}, minmax(210px, 1fr))` }}><div className="p-2 text-center text-xs font-semibold text-slate-400">{time}</div>{courts.map((court) => { const booking = bookings.find((item) => item.courtId === court.id && item.startTime.slice(0, 2) === time.slice(0, 2)); const lock = locked(court.id, time, date); return <div key={court.id} className="border-l border-slate-100 p-1.5">{booking ? <button onClick={() => onBooking(booking)} className={`h-full w-full rounded-lg border p-2 text-left text-xs ${statusColors[booking.status]}`}><b className="block truncate">{booking.customer}</b><span>{booking.startTime}–{booking.endTime} · {booking.id}</span></button> : lock ? <div className="flex h-full items-center justify-center gap-1 rounded-lg bg-slate-200 text-xs font-semibold text-slate-500"><LockKeyhole size={14} />{lock.reason}</div> : <button onClick={() => onSlot(court.id, time)} className="group h-full w-full rounded-lg border border-dashed border-transparent text-xs text-slate-300 hover:border-brand-300 hover:bg-brand-50 hover:text-brand-700"><Plus size={15} className="mx-auto opacity-0 group-hover:opacity-100" />Trống</button>}</div>; })}</div>)}</div></div>; }
function WeekView({ dates, bookings, onBooking }: { dates: string[]; bookings: ManagementBooking[]; onBooking: (booking: ManagementBooking) => void }) { return <div className="overflow-x-auto p-3"><div className="grid min-w-[980px] grid-cols-7 gap-2">{dates.map((date) => <div key={date} className="min-h-[470px] rounded-xl border border-slate-200 bg-slate-50/60"><div className="border-b border-slate-200 p-3 text-center"><b className="block text-xs uppercase text-slate-500">{new Date(`${date}T00:00`).toLocaleDateString('vi-VN', { weekday: 'short' })}</b><span className="text-lg font-bold">{date.slice(8, 10)}</span></div><div className="space-y-2 p-2">{bookings.filter((item) => item.date === date && item.status !== 'cancelled').sort((a, b) => a.startTime.localeCompare(b.startTime)).map((item) => <button key={item.id} onClick={() => onBooking(item)} className={`w-full rounded-lg border p-2 text-left text-[11px] ${statusColors[item.status]}`}><b className="block">{item.startTime} · {item.court}</b><span className="block truncate">{item.customer}</span></button>)}</div></div>)}</div></div>; }
function ListView({ bookings, onBooking }: { bookings: ManagementBooking[]; onBooking: (booking: ManagementBooking) => void }) { return <div className="divide-y divide-slate-100 p-4">{bookings.length ? bookings.sort((a, b) => a.startTime.localeCompare(b.startTime)).map((item) => <button key={item.id} onClick={() => onBooking(item)} className="flex w-full flex-col gap-3 py-4 text-left hover:bg-slate-50 sm:flex-row sm:items-center"><div className="w-24"><b className="text-brand-700">{item.startTime}</b><span className="text-xs text-slate-400"> – {item.endTime}</span></div><div className="flex-1"><b className="text-sm">{item.court} · {item.customer}</b><p className="text-xs text-slate-500">{item.id} · {item.phone}</p></div><Badge variant={bookingStatus[item.status].variant}>{bookingStatus[item.status].label}</Badge></button>) : <p className="py-12 text-center text-sm text-slate-500">Không có booking trong ngày đã chọn.</p>}</div>; }
function Legend({ color, text }: { color: string; text: string }) { return <span className="flex items-center gap-1.5"><i className={`h-3 w-3 rounded border ${color}`} />{text}</span>; }

