import { AlertTriangle, CalendarClock, CheckCircle2, CirclePlay, Pencil, Wrench, XCircle } from 'lucide-react';
import { useEffect, useMemo, useState, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { Badge, Button, EmptyState, Input, LoadingSkeleton, Modal, PageHeader, useToast } from '@/components/common';
import { apiRequest } from '@/services/apiClient';

type Status = 'SCHEDULED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
interface FieldItem { id: number; facility_id: number | null; name: string; }
interface Facility { id: number; name: string; }
interface AffectedBooking { id: number; booking_code: string; customer_name: string; starts_at: string; ends_at: string; status: string; paid_amount: number; }
interface Maintenance { id: number; field_id: number; field_name: string; facility_id: number | null; facility_name: string; maintenance_type: string; title: string; starts_at: string; ends_at: string; priority: 'LOW'|'MEDIUM'|'HIGH'|'URGENT'; notes: string | null; estimated_cost: number | null; actual_cost: number | null; status: Status; created_by_name: string; affected_bookings: AffectedBooking[]; }
interface Summary { upcoming: number; in_progress: number; completed: number; cancelled: number; }

const statusLabel: Record<Status, string> = { SCHEDULED: 'Đã lên lịch', IN_PROGRESS: 'Đang bảo trì', COMPLETED: 'Đã hoàn thành', CANCELLED: 'Đã hủy' };
const priorityLabel = { LOW: 'Thấp', MEDIUM: 'Trung bình', HIGH: 'Cao', URGENT: 'Khẩn cấp' };
const typeLabel: Record<string, string> = { preventive: 'Bảo trì định kỳ', repair: 'Sửa chữa', inspection: 'Kiểm tra', surface: 'Mặt sân', equipment: 'Thiết bị' };
const money = (value: number | null) => value == null ? '—' : `${value.toLocaleString('vi-VN')}đ`;
const localInput = (value: string) => { const date = new Date(value); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); };
const localDate = (value: string) => localInput(value).slice(0, 10);
const emptyForm = { field_id: 0, maintenance_type: 'preventive', title: '', starts_at: '', ends_at: '', priority: 'MEDIUM', notes: '', estimated_cost: '', actual_cost: '' };

export function ManagementMaintenancePage() {
  const { toast } = useToast(); const [items, setItems] = useState<Maintenance[]>([]); const [summary, setSummary] = useState<Summary>();
  const [fields, setFields] = useState<FieldItem[]>([]); const [facilities, setFacilities] = useState<Facility[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false);
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Maintenance>(); const [detail, setDetail] = useState<Maintenance>(); const [form, setForm] = useState(emptyForm);
  const [filters, setFilters] = useState({ field: '', facility: '', status: '', type: '', date: '' });
  const load = async () => { const [maintenance, nextSummary, fieldResult, facilityResult] = await Promise.all([apiRequest<Maintenance[]>('/maintenance'), apiRequest<Summary>('/maintenance/summary'), apiRequest<{items: FieldItem[]}>('/fields?page_size=100'), apiRequest<Facility[]>('/facilities')]); setItems(maintenance); setSummary(nextSummary); setFields(fieldResult.items); setFacilities(facilityResult); };
  useEffect(() => { load().catch((error) => toast(error instanceof Error ? error.message : 'Không tải được lịch bảo trì.', 'error')).finally(() => setLoading(false)); }, []);
  const shown = useMemo(() => items.filter((item) => (!filters.field || item.field_id === Number(filters.field)) && (!filters.facility || item.facility_id === Number(filters.facility)) && (!filters.status || item.status === filters.status) && (!filters.type || item.maintenance_type === filters.type) && (!filters.date || (localDate(item.starts_at) <= filters.date && localDate(item.ends_at) >= filters.date))), [items, filters]);
  const types = Array.from(new Set(items.map((item) => item.maintenance_type)));
  const startCreate = () => { setEditing(undefined); setForm({ ...emptyForm, field_id: fields[0]?.id || 0 }); setOpen(true); };
  const startEdit = (item: Maintenance) => { setEditing(item); setForm({ field_id: item.field_id, maintenance_type: item.maintenance_type, title: item.title, starts_at: localInput(item.starts_at), ends_at: localInput(item.ends_at), priority: item.priority, notes: item.notes || '', estimated_cost: item.estimated_cost == null ? '' : String(item.estimated_cost), actual_cost: item.actual_cost == null ? '' : String(item.actual_cost) }); setOpen(true); };
  const save = async (event: FormEvent) => { event.preventDefault(); if (!form.field_id || !form.starts_at || !form.ends_at) return; setBusy(true); try { const payload = { ...form, starts_at: new Date(form.starts_at).toISOString(), ends_at: new Date(form.ends_at).toISOString(), estimated_cost: form.estimated_cost === '' ? null : Number(form.estimated_cost), actual_cost: form.actual_cost === '' ? null : Number(form.actual_cost), notes: form.notes || null }; const result = await apiRequest<Maintenance>(editing ? `/maintenance/${editing.id}` : '/maintenance', { method: editing ? 'PUT' : 'POST', body: JSON.stringify(payload) }); setOpen(false); setDetail(result); await load(); toast(result.affected_bookings.length ? `Đã lưu. Có ${result.affected_bookings.length} booking bị ảnh hưởng cần xử lý.` : 'Đã lưu lịch bảo trì.', result.affected_bookings.length ? 'info' : 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không lưu được lịch bảo trì.', 'error'); } finally { setBusy(false); } };
  const transition = async (item: Maintenance, action: 'start'|'complete'|'cancel') => { if (action === 'cancel' && !window.confirm('Hủy lịch bảo trì và mở lại các slot liên quan?')) return; setBusy(true); try { const result = await apiRequest<Maintenance>(`/maintenance/${item.id}/${action}`, { method: 'PATCH' }); setDetail(result); await load(); toast(action === 'cancel' ? 'Đã hủy bảo trì, slot được mở lại nếu không còn ràng buộc khác.' : 'Đã cập nhật trạng thái bảo trì.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không cập nhật được bảo trì.', 'error'); } finally { setBusy(false); } };
  return <><PageHeader title="Quản lý bảo trì sân" description="Lập kế hoạch, theo dõi chi phí và xử lý booking bị ảnh hưởng trên dữ liệu vận hành thật." actions={<Button leftIcon={<Wrench size={16}/>} disabled={!fields.length} onClick={startCreate}>Tạo lịch bảo trì</Button>} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Sắp tới" value={summary?.upcoming || 0}/><Metric label="Đang bảo trì" value={summary?.in_progress || 0}/><Metric label="Đã hoàn thành" value={summary?.completed || 0}/><Metric label="Đã hủy" value={summary?.cancelled || 0}/></div>
    <section className="my-5 grid gap-3 rounded-card border bg-white p-4 sm:grid-cols-2 xl:grid-cols-5"><Select value={filters.facility} onChange={(value) => setFilters({...filters, facility:value})} label="Cơ sở" options={facilities.map((x)=>[String(x.id),x.name])}/><Select value={filters.field} onChange={(value) => setFilters({...filters, field:value})} label="Sân" options={fields.map((x)=>[String(x.id),x.name])}/><Select value={filters.status} onChange={(value) => setFilters({...filters, status:value})} label="Trạng thái" options={Object.entries(statusLabel)}/><Select value={filters.type} onChange={(value) => setFilters({...filters, type:value})} label="Loại" options={types.map((x)=>[x,x])}/><Input type="date" label="Ngày" value={filters.date} onChange={(event)=>setFilters({...filters,date:event.target.value})}/></section>
    {loading ? <LoadingSkeleton lines={8}/> : shown.length ? <div className="overflow-x-auto rounded-card border bg-white"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Sân / cơ sở','Nội dung','Thời gian','Ưu tiên','Chi phí','Trạng thái','Thao tác'].map((x)=><th key={x} className="px-4 py-3">{x}</th>)}</tr></thead><tbody>{shown.map((item)=><tr key={item.id} className="border-t"><td className="px-4 py-3"><b>{item.field_name}</b><small className="block text-slate-500">{item.facility_name}</small></td><td className="px-4 py-3"><button className="font-semibold text-brand-700 hover:underline" onClick={()=>setDetail(item)}>{item.title}</button><small className="block text-slate-500">{item.maintenance_type}</small>{item.affected_bookings.length>0&&<span className="mt-1 flex items-center gap-1 text-xs font-semibold text-amber-700"><AlertTriangle size={13}/>{item.affected_bookings.length} booking bị ảnh hưởng</span>}</td><td className="px-4 py-3">{new Date(item.starts_at).toLocaleString('vi-VN')}<span className="block text-slate-500">đến {new Date(item.ends_at).toLocaleString('vi-VN')}</span></td><td className="px-4 py-3">{priorityLabel[item.priority]}</td><td className="px-4 py-3">{money(item.estimated_cost)}<small className="block">Thực tế: {money(item.actual_cost)}</small></td><td className="px-4 py-3"><Badge variant={item.status==='COMPLETED'?'success':item.status==='IN_PROGRESS'?'warning':'neutral'}>{statusLabel[item.status]}</Badge></td><td className="px-4 py-3"><div className="flex gap-1">{['SCHEDULED','IN_PROGRESS'].includes(item.status)&&<Button size="sm" variant="outline" onClick={()=>startEdit(item)}><Pencil size={14}/></Button>}{item.status==='SCHEDULED'&&<Button size="sm" onClick={()=>void transition(item,'start')}><CirclePlay size={14}/></Button>}{item.status==='IN_PROGRESS'&&<Button size="sm" onClick={()=>void transition(item,'complete')}><CheckCircle2 size={14}/></Button>}{['SCHEDULED','IN_PROGRESS'].includes(item.status)&&<Button size="sm" variant="danger" onClick={()=>void transition(item,'cancel')}><XCircle size={14}/></Button>}</div></td></tr>)}</tbody></table></div> : <EmptyState icon={<CalendarClock/>} title="Không có lịch bảo trì phù hợp" description="Tạo lịch mới hoặc điều chỉnh bộ lọc."/>}
    <Modal open={open} onClose={()=>setOpen(false)} title={editing?'Sửa lịch bảo trì':'Tạo lịch bảo trì'}><form onSubmit={save} className="grid gap-4 sm:grid-cols-2"><Select value={String(form.field_id||'')} onChange={(value)=>setForm({...form,field_id:Number(value)})} label="Sân" options={fields.map((x)=>[String(x.id),x.name])} required/><Input required label="Tiêu đề / lý do" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/><Select value={form.maintenance_type} onChange={(value)=>setForm({...form,maintenance_type:value})} label="Loại bảo trì" options={[['preventive','Định kỳ'],['repair','Sửa chữa'],['inspection','Kiểm tra'],['surface','Mặt sân'],['equipment','Thiết bị']]}/><Select value={form.priority} onChange={(value)=>setForm({...form,priority:value})} label="Ưu tiên" options={Object.entries(priorityLabel)}/><Input required type="datetime-local" label="Bắt đầu" value={form.starts_at} onChange={(e)=>setForm({...form,starts_at:e.target.value})}/><Input required type="datetime-local" label="Kết thúc" value={form.ends_at} onChange={(e)=>setForm({...form,ends_at:e.target.value})}/><Input type="number" min={0} label="Chi phí dự kiến" value={form.estimated_cost} onChange={(e)=>setForm({...form,estimated_cost:e.target.value})}/><Input type="number" min={0} label="Chi phí thực tế" value={form.actual_cost} onChange={(e)=>setForm({...form,actual_cost:e.target.value})}/><label className="text-sm font-medium sm:col-span-2">Ghi chú<textarea className="field mt-1 min-h-24" value={form.notes} onChange={(e)=>setForm({...form,notes:e.target.value})}/></label><Button type="submit" loading={busy} className="sm:col-span-2">Lưu lịch bảo trì</Button></form></Modal>
    <Modal open={Boolean(detail)} onClose={()=>setDetail(undefined)} title={detail?.title||'Chi tiết bảo trì'}>{detail&&<div className="space-y-4 text-sm"><p><b>{detail.field_name}</b> · {detail.facility_name}</p><p>{new Date(detail.starts_at).toLocaleString('vi-VN')} – {new Date(detail.ends_at).toLocaleString('vi-VN')}</p><p><b>Trạng thái:</b> {statusLabel[detail.status]} · <b>Ưu tiên:</b> {priorityLabel[detail.priority]}</p>{detail.notes&&<p className="rounded-lg bg-slate-50 p-3">{detail.notes}</p>}{detail.affected_bookings.length>0&&<section className="rounded-xl border border-amber-200 bg-amber-50 p-4"><h3 className="flex items-center gap-2 font-bold text-amber-900"><AlertTriangle size={17}/>Booking cần xử lý</h3><p className="mt-1 text-xs text-amber-800">Hệ thống không tự hủy. Mở booking để áp dụng đúng luồng hủy và hoàn tiền hiện có.</p><div className="mt-3 space-y-2">{detail.affected_bookings.map((booking)=><Link key={booking.id} to={`/management/bookings/${booking.id}`} className="block rounded-lg bg-white p-3 hover:ring-1 hover:ring-amber-300"><b>{booking.booking_code}</b> · {booking.customer_name}<span className="block text-xs text-slate-500">{new Date(booking.starts_at).toLocaleString('vi-VN')} · Đã trả {money(booking.paid_amount)}</span></Link>)}</div></section>}</div>}</Modal>
  </>;
}
function Metric({label,value}:{label:string;value:number}){return <article className="rounded-card border bg-white p-4"><p className="text-xs text-slate-500">{label}</p><b className="mt-2 block text-2xl">{value}</b></article>}
function Select({label,value,onChange,options,required}:{label:string;value:string;onChange:(v:string)=>void;options:Array<[string,string]>;required?:boolean}){return <label className="text-sm font-medium">{label}<select required={required} className="field mt-1" value={value} onChange={(e)=>onChange(e.target.value)}>{!required&&<option value="">Tất cả</option>}{required&&<option value="">Chọn</option>}{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
