import { Building2, FileText, ImagePlus, MapPin, Pencil, Phone, Plus, Send, ShieldCheck, Trash2, XCircle } from 'lucide-react';
import { type FormEvent, useEffect, useState } from 'react';
import { Badge, Button, EmptyState, Input, LoadingSkeleton, Modal, PageHeader, SecureApiImage, useToast } from '@/components/common';
import { apiRequest } from '@/services/apiClient';

type Status = 'DRAFT' | 'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';
interface Media { id: number; category?: string; document_name?: string; document_type?: string; document_number?: string; issued_date?: string; issued_by?: string; original_name: string; url?: string; }
interface Facility { id: number; name: string; location: string; description: string | null; contact_phone: string | null; contact_email: string | null; city: string | null; district: string | null; opening_time: string | null; closing_time: string | null; sports: string[]; status: Status; submitted_at: string | null; rejection_reason: string | null; field_count: number; images: Media[]; documents: Media[]; }
const sports = ['Bóng đá', 'Cầu lông', 'Pickleball', 'Tennis', 'Bóng rổ', 'Bóng chuyền'];
const labels: Record<Status, string> = { DRAFT: 'Bản nháp', PENDING_REVIEW: 'Chờ xét duyệt', APPROVED: 'Đã duyệt', REJECTED: 'Cần bổ sung', SUSPENDED: 'Tạm ngừng' };
const badge = (status: Status) => status === 'APPROVED' ? 'success' : status === 'REJECTED' || status === 'SUSPENDED' ? 'danger' : status === 'PENDING_REVIEW' ? 'warning' : 'neutral';
const blank = { name: '', location: '', description: '', contact_phone: '', contact_email: '', city: '', district: '', opening_time: '06:00', closing_time: '22:00', sports: [] as string[] };

export function ManagementVenuesPage() {
  const [items, setItems] = useState<Facility[]>([]); const [loading, setLoading] = useState(true);
  const [editing, setEditing] = useState<Facility>(); const [open, setOpen] = useState(false);
  const [form, setForm] = useState(blank); const [saving, setSaving] = useState(false);
  const [imageCategory, setImageCategory] = useState('COVER'); const [documentType, setDocumentType] = useState('BUSINESS_LICENSE'); const [documentName, setDocumentName] = useState('');
  const [documentNumber, setDocumentNumber] = useState(''); const [issuedDate, setIssuedDate] = useState(''); const [issuedBy, setIssuedBy] = useState('');
  const { toast } = useToast();
  const load = async () => { setLoading(true); try { setItems(await apiRequest<Facility[]>('/facilities')); } catch (error) { toast(error instanceof Error ? error.message : 'Không tải được cơ sở.', 'error'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const startCreate = () => { setEditing(undefined); setForm(blank); setOpen(true); };
  const startEdit = (item: Facility) => { setEditing(item); setForm({ name: item.name, location: item.location, description: item.description || '', contact_phone: item.contact_phone || '', contact_email: item.contact_email || '', city: item.city || '', district: item.district || '', opening_time: item.opening_time?.slice(0, 5) || '06:00', closing_time: item.closing_time?.slice(0, 5) || '22:00', sports: item.sports || [] }); setOpen(true); };
  const save = async (event: FormEvent) => {
    event.preventDefault();
    if (!form.sports.length) return toast('Chọn ít nhất một môn thể thao.', 'error');
    if (form.opening_time >= form.closing_time) return toast('Giờ mở cửa phải trước giờ đóng cửa.', 'error');
    setSaving(true);
    try {
      const updated = await apiRequest<Facility>(editing ? '/facilities/' + editing.id : '/facilities', { method: editing ? 'PUT' : 'POST', body: JSON.stringify({ ...form, free_cancellation_minutes: 360, amenities: [], image_urls: [] }) });
      setEditing(updated); setItems((current) => editing ? current.map((item) => item.id === updated.id ? updated : item) : [updated, ...current]);
      toast(editing ? 'Đã cập nhật hồ sơ cơ sở.' : 'Đã tạo bản nháp. Bạn có thể tải ảnh và tài liệu ngay.', 'success');
    } catch (error) { toast(error instanceof Error ? error.message : 'Không lưu được hồ sơ.', 'error'); } finally { setSaving(false); }
  };
  const uploadImage = async (file?: File) => {
    if (!editing || !file) return; const body = new FormData(); body.append('category', imageCategory); body.append('image', file); setSaving(true);
    try { const updated = await apiRequest<Facility>('/facilities/' + editing.id + '/images', { method: 'POST', body }); setEditing(updated); setItems((current) => current.map((item) => item.id === updated.id ? updated : item)); toast('Đã tải ảnh cơ sở.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không tải được ảnh.', 'error'); } finally { setSaving(false); }
  };
  const uploadDocument = async (file?: File) => {
    if (!editing || !file || documentName.trim().length < 2) return toast('Nhập tên tài liệu trước khi tải.', 'error');
    const body = new FormData(); body.append('document_type', documentType); body.append('document_name', documentName.trim()); if (documentNumber.trim()) body.append('document_number', documentNumber.trim()); if (issuedDate) body.append('issued_date', issuedDate); if (issuedBy.trim()) body.append('issued_by', issuedBy.trim()); body.append('document', file); setSaving(true);
    try { const updated = await apiRequest<Facility>('/facilities/' + editing.id + '/documents', { method: 'POST', body }); setEditing(updated); setItems((current) => current.map((item) => item.id === updated.id ? updated : item)); setDocumentName(''); setDocumentNumber(''); setIssuedDate(''); setIssuedBy(''); toast('Đã tải tài liệu xác minh.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không tải được tài liệu.', 'error'); } finally { setSaving(false); }
  };
  const removeMedia = async (kind: 'images' | 'documents', mediaId: number) => {
    if (!editing || !window.confirm(kind === 'images' ? 'Xóa ảnh này khỏi hồ sơ?' : 'Xóa tài liệu này khỏi hồ sơ?')) return;
    setSaving(true);
    try { const updated = await apiRequest<Facility>('/facilities/' + editing.id + '/' + kind + '/' + mediaId, { method: 'DELETE' }); setEditing(updated); setItems((current) => current.map((item) => item.id === updated.id ? updated : item)); toast(kind === 'images' ? 'Đã xóa ảnh.' : 'Đã xóa tài liệu.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không thể xóa tệp.', 'error'); } finally { setSaving(false); }
  };
  const action = async (item: Facility, endpoint: string, success: string) => {
    setSaving(true); try { const updated = await apiRequest<Facility>('/facilities/' + item.id + '/' + endpoint, { method: 'POST' }); setItems((current) => current.map((value) => value.id === updated.id ? updated : value)); if (editing?.id === updated.id) setEditing(updated); toast(success, 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không xử lý được hồ sơ.', 'error'); } finally { setSaving(false); }
  };

  return <><PageHeader title="Cơ sở" description="Đăng ký, theo dõi xét duyệt và quản lý các cơ sở thuộc tài khoản OWNER." actions={<Button leftIcon={<Plus size={17} />} onClick={startCreate}>Đăng ký cơ sở mới</Button>} />
    {loading ? <LoadingSkeleton lines={8} /> : items.length ? <div className="grid gap-5 lg:grid-cols-2">{items.map((item) => <article key={item.id} className="overflow-hidden rounded-card border bg-white shadow-sm">
      {item.images[0]?.url ? <SecureApiImage src={item.images[0].url} alt={item.name} className="h-44 w-full object-cover" /> : <div className="grid h-32 place-items-center bg-gradient-to-br from-brand-50 to-sportblue-50 text-brand-700"><Building2 size={40} /></div>}
      <div className="p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-black">{item.name}</h2><p className="mt-1 flex gap-2 text-sm text-slate-500"><MapPin size={16} />{item.location}</p></div><Badge variant={badge(item.status)}>{labels[item.status]}</Badge></div>
      <div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-sm"><span><Phone size={15} className="mr-1 inline" />{item.contact_phone || 'Chưa có hotline'}</span><span>{item.field_count} sân/court</span><span className="col-span-2">{item.sports.join(' · ') || 'Chưa chọn môn'}</span></div>
      {item.rejection_reason && <p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-700"><b>Phản hồi:</b> {item.rejection_reason}</p>}
      {item.submitted_at && <p className="mt-3 text-xs text-slate-500">Gửi xét duyệt: {new Date(item.submitted_at).toLocaleString('vi-VN')}</p>}
      <div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" leftIcon={<Pencil size={15} />} onClick={() => startEdit(item)}>{item.status === 'PENDING_REVIEW' ? 'Xem hồ sơ' : item.status === 'REJECTED' ? 'Bổ sung hồ sơ' : 'Chỉnh sửa'}</Button>{['DRAFT', 'REJECTED'].includes(item.status) && <Button size="sm" leftIcon={<Send size={15} />} loading={saving} onClick={() => void action(item, 'submit', 'Đã gửi hồ sơ xét duyệt.')}>Gửi xét duyệt</Button>}{item.status === 'PENDING_REVIEW' && <Button size="sm" variant="danger" leftIcon={<XCircle size={15} />} onClick={() => void action(item, 'cancel-review', 'Đã hủy yêu cầu xét duyệt.')}>Hủy yêu cầu</Button>}{item.status === 'APPROVED' && <Button size="sm" onClick={() => location.assign('/management/courts')}>Quản lý sân</Button>}</div>
      </div></article>)}</div> : <EmptyState icon={<Building2 />} title="Chưa có cơ sở" description="Tạo hồ sơ cơ sở đầu tiên để gửi System Admin xét duyệt." />}
    <Modal open={open} onClose={() => !saving && setOpen(false)} title={editing ? 'Hồ sơ cơ sở' : 'Đăng ký cơ sở mới'} description="Thông tin xác minh chỉ hiển thị cho OWNER sở hữu và System Admin.">
      <form onSubmit={save} className="space-y-4"><Input required label="Tên cơ sở" value={form.name} disabled={editing?.status === 'PENDING_REVIEW'} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input required label="Địa chỉ đầy đủ" value={form.location} disabled={editing?.status === 'PENDING_REVIEW'} onChange={(e) => setForm({ ...form, location: e.target.value })} /><div className="grid gap-3 sm:grid-cols-2"><Input label="Tỉnh/thành phố" value={form.city} disabled={editing?.status === 'PENDING_REVIEW'} onChange={(e) => setForm({ ...form, city: e.target.value })} /><Input label="Quận/huyện/khu vực" value={form.district} disabled={editing?.status === 'PENDING_REVIEW'} onChange={(e) => setForm({ ...form, district: e.target.value })} /><Input required label="Hotline" value={form.contact_phone} disabled={editing?.status === 'PENDING_REVIEW'} onChange={(e) => setForm({ ...form, contact_phone: e.target.value })} /><Input type="email" label="Email liên hệ" value={form.contact_email} disabled={editing?.status === 'PENDING_REVIEW'} onChange={(e) => setForm({ ...form, contact_email: e.target.value })} /><Input required type="time" label="Giờ mở cửa" value={form.opening_time} disabled={editing?.status === 'PENDING_REVIEW'} onChange={(e) => setForm({ ...form, opening_time: e.target.value })} /><Input required type="time" label="Giờ đóng cửa" value={form.closing_time} disabled={editing?.status === 'PENDING_REVIEW'} onChange={(e) => setForm({ ...form, closing_time: e.target.value })} /></div>
      <label className="block text-sm font-medium">Mô tả<textarea required className="field mt-2 min-h-24" value={form.description} disabled={editing?.status === 'PENDING_REVIEW'} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label>
      <fieldset disabled={editing?.status === 'PENDING_REVIEW'}><legend className="text-sm font-semibold">Môn thể thao</legend><div className="mt-2 grid grid-cols-2 gap-2">{sports.map((sport) => <label key={sport} className="flex items-center gap-2 rounded-lg border p-2 text-sm"><input type="checkbox" checked={form.sports.includes(sport)} onChange={(e) => setForm({ ...form, sports: e.target.checked ? [...form.sports, sport] : form.sports.filter((value) => value !== sport) })} />{sport}</label>)}</div></fieldset>
      {editing?.status !== 'PENDING_REVIEW' && <Button type="submit" loading={saving} className="w-full">{editing ? 'Lưu thay đổi' : 'Tạo bản nháp'}</Button>}</form>
      {editing && <div className="mt-6 space-y-5 border-t pt-5"><section><h3 className="flex items-center gap-2 font-bold"><ImagePlus size={18} />Hình ảnh cơ sở</h3>{editing.status !== 'PENDING_REVIEW' && <div className="mt-3 flex gap-2"><select className="field" value={imageCategory} onChange={(e) => setImageCategory(e.target.value)}><option value="COVER">Ảnh đại diện</option><option value="FRONT">Ảnh mặt tiền</option><option value="COURT_AREA">Khu vực sân</option><option value="ADDITIONAL">Ảnh bổ sung</option></select><label className="inline-flex cursor-pointer items-center rounded-xl bg-brand-600 px-4 text-sm font-semibold text-white">Tải ảnh<input className="sr-only" type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => void uploadImage(e.target.files?.[0])} /></label></div>}<div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3">{editing.images.map((image) => <div key={image.id} className="relative"><SecureApiImage src={image.url} alt={image.original_name} className="h-24 w-full rounded-lg object-cover" />{editing.status !== 'PENDING_REVIEW' && <button type="button" aria-label="Xóa ảnh" className="absolute right-1 top-1 rounded-full bg-white/90 p-1.5 text-red-600 shadow" onClick={() => void removeMedia('images', image.id)}><Trash2 size={14} /></button>}</div>)}</div></section>
      <section><h3 className="flex items-center gap-2 font-bold"><FileText size={18} />Tài liệu xác minh</h3>{editing.status !== 'PENDING_REVIEW' && <div className="mt-3 grid gap-2"><select className="field" value={documentType} onChange={(e) => setDocumentType(e.target.value)}><option value="BUSINESS_LICENSE">Giấy phép/đăng ký kinh doanh</option><option value="LOCATION_RIGHT">Quyền quản lý địa điểm</option><option value="SIGNAGE">Mặt tiền/biển hiệu</option><option value="OTHER">Tài liệu khác</option></select><Input placeholder="Tên tài liệu" value={documentName} onChange={(e) => setDocumentName(e.target.value)} /><div className="grid gap-2 sm:grid-cols-2"><Input placeholder="Số giấy tờ (nếu có)" value={documentNumber} onChange={(e) => setDocumentNumber(e.target.value)} /><Input type="date" aria-label="Ngày cấp" value={issuedDate} onChange={(e) => setIssuedDate(e.target.value)} /><Input placeholder="Nơi cấp (nếu có)" value={issuedBy} onChange={(e) => setIssuedBy(e.target.value)} /></div><label className="inline-flex h-11 cursor-pointer items-center justify-center rounded-xl border border-brand-300 bg-brand-50 font-semibold text-brand-700">Chọn PDF hoặc ảnh<input className="sr-only" type="file" accept="application/pdf,image/jpeg,image/png,image/webp" onChange={(e) => void uploadDocument(e.target.files?.[0])} /></label></div>}<ul className="mt-3 space-y-2">{editing.documents.map((doc) => <li key={doc.id} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 p-2 text-sm"><span><ShieldCheck size={15} className="mr-2 inline text-brand-700" />{doc.document_name} · {doc.original_name}{doc.document_number ? ` · Số ${doc.document_number}` : ''}</span>{editing.status !== 'PENDING_REVIEW' && <button type="button" aria-label="Xóa tài liệu" className="shrink-0 rounded-lg p-2 text-red-600 hover:bg-red-50" onClick={() => void removeMedia('documents', doc.id)}><Trash2 size={15} /></button>}</li>)}</ul></section></div>}
    </Modal>
  </>;
}