import { useEffect, useState } from 'react';
import { Button, EmptyState, Input, LoadingSkeleton, PageHeader, useToast } from '@/components/common';
import { useAuth } from '@/contexts/AuthContext';
import { apiRequest } from '@/services/apiClient';

interface FieldConfig { id: number; name: string; location: string; deposit_type: 'percentage' | 'fixed'; deposit_value: number; }
interface FacilityConfig { id: number; name: string; location: string; free_cancellation_minutes: number; }
interface PriceSlot { id: number; field_id: number; name: string; start_time: string; end_time: string; price: number; weekday_price: number | null; weekend_price: number | null; is_active: boolean; }
export function ManagementDepositSettingsPage() {
  const { user } = useAuth(); const { toast } = useToast(); const [fields, setFields] = useState<FieldConfig[]>([]); const [facilities, setFacilities] = useState<FacilityConfig[]>([]);
  const [slots, setSlots] = useState<PriceSlot[]>([]); const [priceSlotId, setPriceSlotId] = useState(0);
  const [fieldId, setFieldId] = useState(0); const [facilityId, setFacilityId] = useState(0); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  const [newFacility, setNewFacility] = useState({ name: '', location: '' });
  useEffect(() => { Promise.all([apiRequest<{ items: FieldConfig[] }>('/fields?page_size=100'), user?.role === 'OWNER' ? apiRequest<FacilityConfig[]>('/facilities') : Promise.resolve([]), apiRequest<PriceSlot[]>('/time-slots')]).then(([fieldResult, facilityResult, slotResult]) => { setFields(fieldResult.items); setFieldId(fieldResult.items[0]?.id || 0); setFacilities(facilityResult); setFacilityId(facilityResult[0]?.id || 0); setSlots(slotResult); setPriceSlotId(slotResult[0]?.id || 0); }).catch((error) => toast(error instanceof Error ? error.message : 'Không tải được cấu hình.', 'error')).finally(() => setLoading(false)); }, [user?.role]);
  const field = fields.find((item) => item.id === fieldId); const facility = facilities.find((item) => item.id === facilityId);
  const priceSlot = slots.find((item) => item.id === priceSlotId);
  const patchField = (values: Partial<FieldConfig>) => setFields((current) => current.map((item) => item.id === fieldId ? { ...item, ...values } : item));
  const patchFacility = (values: Partial<FacilityConfig>) => setFacilities((current) => current.map((item) => item.id === facilityId ? { ...item, ...values } : item));
  const patchPriceSlot = (values: Partial<PriceSlot>) => setSlots((current) => current.map((item) => item.id === priceSlotId ? { ...item, ...values } : item));
  const savePrice = async () => { if (!priceSlot) return; setSaving(true); try { const updated = await apiRequest<PriceSlot>(`/time-slots/${priceSlot.id}`, { method: 'PUT', body: JSON.stringify(priceSlot) }); setSlots((current) => current.map((item) => item.id === updated.id ? updated : item)); toast('Đã lưu bảng giá khung giờ. Giá CUSTOMER được backend lấy từ cấu hình này.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không thể lưu bảng giá.', 'error'); } finally { setSaving(false); } };
  const saveField = async () => { if (!field) return; setSaving(true); try { const updated = await apiRequest<FieldConfig>(`/fields/${field.id}`, { method: 'PUT', body: JSON.stringify({ deposit_type: field.deposit_type, deposit_value: field.deposit_value }) }); patchField(updated); toast('Đã lưu mức đặt cọc.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không thể lưu mức cọc.', 'error'); } finally { setSaving(false); } };
  const savePolicy = async () => { if (!facility) return; setSaving(true); try { const updated = await apiRequest<FacilityConfig>(`/facilities/${facility.id}/cancellation-policy`, { method: 'PUT', body: JSON.stringify({ free_cancellation_minutes: facility.free_cancellation_minutes }) }); setFacilities((current) => current.map((item) => item.id === updated.id ? updated : item)); toast('Đã lưu chính sách hủy của cơ sở.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không thể lưu chính sách hủy.', 'error'); } finally { setSaving(false); } };
  const createFacility = async () => { if (newFacility.name.trim().length < 2 || newFacility.location.trim().length < 3) return toast('Nhập đủ tên và địa chỉ cơ sở.', 'error'); setSaving(true); try { const created = await apiRequest<FacilityConfig>('/facilities', { method: 'POST', body: JSON.stringify(newFacility) }); setFacilities((current) => [...current, created]); setFacilityId(created.id); setNewFacility({ name: '', location: '' }); toast('Đã tạo cơ sở.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không thể tạo cơ sở.', 'error'); } finally { setSaving(false); } };
  if (loading) return <LoadingSkeleton lines={8} />;
  return <><PageHeader title="Giá, đặt cọc và chính sách hủy" description="Backend snapshot mức cọc vào booking; chính sách hủy được cấu hình riêng theo cơ sở." />
    {priceSlot ? <section className="mb-5 rounded-card border bg-white p-5"><h2 className="font-bold">Bảng giá theo khung giờ</h2><p className="mt-1 text-xs text-slate-500">Đây là nơi duy nhất trên giao diện OWNER chỉnh giá slot. Backend áp dụng giá ngày thường/cuối tuần khi CUSTOMER đặt sân.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-medium">Khung giờ<select className="field mt-2" value={priceSlotId} onChange={(event) => setPriceSlotId(Number(event.target.value))}>{slots.map((item) => <option key={item.id} value={item.id}>{fields.find((field) => field.id === item.field_id)?.name} · {item.name} · {item.start_time.slice(0,5)}–{item.end_time.slice(0,5)}</option>)}</select></label><Input label="Giá mặc định" type="number" min={0} value={priceSlot.price} onChange={(event) => patchPriceSlot({ price: Number(event.target.value) })} /><Input label="Giá ngày thường" type="number" min={0} value={priceSlot.weekday_price ?? ''} onChange={(event) => patchPriceSlot({ weekday_price: event.target.value === '' ? null : Number(event.target.value) })} /><Input label="Giá cuối tuần" type="number" min={0} value={priceSlot.weekend_price ?? ''} onChange={(event) => patchPriceSlot({ weekend_price: event.target.value === '' ? null : Number(event.target.value) })} /></div><Button className="mt-4" loading={saving} onClick={() => void savePrice()}>Lưu bảng giá</Button></section> : <div className="mb-5"><EmptyState title="Chưa có khung giờ để định giá" description="Tạo khung giờ trước, sau đó quay lại cấu hình giá." /></div>}
    {field ? <section className="rounded-card border bg-white p-5"><h2 className="font-bold">Mức đặt cọc theo sân</h2><div className="mt-4 grid gap-4 sm:grid-cols-3"><label className="text-sm font-medium">Chọn sân<select className="field mt-2" value={fieldId} onChange={(event) => setFieldId(Number(event.target.value))}>{fields.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">Kiểu đặt cọc<select className="field mt-2" value={field.deposit_type} onChange={(event) => patchField({ deposit_type: event.target.value as FieldConfig['deposit_type'] })}><option value="percentage">Phần trăm</option><option value="fixed">Số tiền cố định</option></select></label><Input label={field.deposit_type === 'percentage' ? 'Mức cọc (%)' : 'Mức cọc (đ)'} type="number" min={0} max={field.deposit_type === 'percentage' ? 100 : undefined} value={field.deposit_value} onChange={(event) => patchField({ deposit_value: Number(event.target.value) })} /></div><Button className="mt-4" loading={saving} onClick={() => void saveField()}>Lưu mức cọc</Button></section> : <EmptyState title="Chưa có sân" description="Tạo sân trước khi cấu hình mức đặt cọc." />}
    {user?.role === 'OWNER' && <section className="mt-5 rounded-card border bg-white p-5"><h2 className="font-bold">Thêm cơ sở</h2><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><Input placeholder="Tên cơ sở" value={newFacility.name} onChange={(event) => setNewFacility({ ...newFacility, name: event.target.value })} /><Input placeholder="Địa chỉ" value={newFacility.location} onChange={(event) => setNewFacility({ ...newFacility, location: event.target.value })} /><Button loading={saving} onClick={() => void createFacility()}>Tạo cơ sở</Button></div></section>}
    {user?.role === 'OWNER' && (facility ? <section className="mt-5 rounded-card border bg-white p-5"><h2 className="font-bold">Chính sách hủy theo cơ sở</h2><label className="mt-4 block text-sm font-medium">Cơ sở<select className="field mt-2" value={facilityId} onChange={(event) => setFacilityId(Number(event.target.value))}>{facilities.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.location}</option>)}</select></label><div className="mt-4 grid gap-4 rounded-xl bg-slate-50 p-4 sm:grid-cols-[1fr_2fr]"><Input label="Hủy miễn phí trước (giờ)" type="number" min={0} step={0.5} value={facility.free_cancellation_minutes / 60} onChange={(event) => patchFacility({ free_cancellation_minutes: Math.round(Number(event.target.value) * 60) })} /><div className="self-end rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800"><b>Quy tắc áp dụng:</b> Hủy trước giờ chơi ít nhất {facility.free_cancellation_minutes / 60} giờ được hoàn 100% tiền cọc. Hủy muộn hơn không được hoàn cọc.</div></div><Button className="mt-4" loading={saving} onClick={() => void savePolicy()}>Lưu chính sách hủy</Button></section> : <div className="mt-5"><EmptyState title="Chưa có cơ sở" description="Tạo cơ sở để cấu hình chính sách và gán sân." /></div>)}
  </>;
}
