import { ArrowLeft, FileImage, Search, X, ZoomIn } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Badge, Button, EmptyState, Input, LoadingSkeleton, PageHeader, useToast } from '@/components/common';
import { apiBlob, apiRequest } from '@/services/apiClient';
import type { OwnerApplicationStatus } from '@/types/auth';

interface PartnerApplication { id: number; customer_id: number; customer_name: string; customer_email: string; customer_phone: string | null; status: OwnerApplicationStatus; representative: Record<string, unknown>; venue: Record<string, unknown>; legal_confirmed: boolean; admin_note: string | null; rejection_reason: string | null; withdraw_reason: string | null; withdrawn_at: string | null; reviewed_by: number | null; reviewer_name: string | null; submitted_at: string | null; reviewed_at: string | null; created_at: string; updated_at: string; has_document: boolean; document_file_name: string | null; document_mime: string | null; document_size: number | null; document_uploaded_at: string | null; }
const labels: Record<OwnerApplicationStatus, string> = { DRAFT: 'Bản nháp', PENDING_REVIEW: 'Chờ xét duyệt', NEED_MORE_INFO: 'Cần bổ sung', APPROVED: 'Đã duyệt', REJECTED: 'Từ chối', WITHDRAWN: 'Đã rút' };
const variant = (status: OwnerApplicationStatus) => status === 'APPROVED' ? 'success' : status === 'REJECTED' ? 'danger' : status === 'PENDING_REVIEW' ? 'warning' : 'neutral';
const show = (value: unknown) => Array.isArray(value) ? value.join(', ') : value ? String(value) : '—';

export function SystemAdminPartnerApplicationsPage() {
  const [items, setItems] = useState<PartnerApplication[]>([]); const [selected, setSelected] = useState<PartnerApplication>();
  const [documentUrl, setDocumentUrl] = useState<string>(); const [zoom, setZoom] = useState(false); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false);
  const [query, setQuery] = useState(''); const [status, setStatus] = useState(''); const [from, setFrom] = useState(''); const [to, setTo] = useState(''); const { toast } = useToast();
  const load = async () => { setLoading(true); try { const params = new URLSearchParams(); if (query.trim()) params.set('search', query.trim()); if (status) params.set('status', status); if (from) params.set('submitted_from', `${from}T00:00:00`); if (to) params.set('submitted_to', `${to}T23:59:59`); setItems(await apiRequest<PartnerApplication[]>(`/admin/owner-applications?${params}`)); } catch (error) { toast(error instanceof Error ? error.message : 'Không tải được hồ sơ đối tác.', 'error'); } finally { setLoading(false); } };
  useEffect(() => { void load(); return () => { if (documentUrl) URL.revokeObjectURL(documentUrl); }; }, []);
  useEffect(() => () => { if (documentUrl) URL.revokeObjectURL(documentUrl); }, [documentUrl]);
  const openDetail = async (item: PartnerApplication) => { setSelected(item); setDocumentUrl(undefined); if (!item.has_document) return; try { const blob = await apiBlob(`/admin/owner-applications/${item.id}/document`); setDocumentUrl(URL.createObjectURL(blob)); } catch (error) { toast(error instanceof Error ? error.message : 'Không tải được ảnh giấy tờ.', 'error'); } };
  const close = () => { if (documentUrl) URL.revokeObjectURL(documentUrl); setDocumentUrl(undefined); setSelected(undefined); setZoom(false); };
  const review = async (action: 'APPROVE' | 'REQUEST_MORE_INFO' | 'REJECT') => { if (!selected) return; const requiresNote = action !== 'APPROVE'; const note = requiresNote ? window.prompt(action === 'REJECT' ? 'Nhập lý do từ chối hồ sơ:' : 'Nhập nội dung khách hàng cần bổ sung:') : window.prompt('Ghi chú nội bộ (không bắt buộc):'); if (requiresNote && (!note || note.trim().length < 3)) return toast('Ghi chú/lý do phải có ít nhất 3 ký tự.', 'error'); setWorking(true); try { const updated = await apiRequest<PartnerApplication>(`/admin/owner-applications/${selected.id}/review`, { method: 'PATCH', body: JSON.stringify({ action, admin_note: note?.trim() || null }) }); setItems((current) => current.map((item) => item.id === updated.id ? updated : item)); setSelected(updated); toast(action === 'APPROVE' ? 'Đã phê duyệt và cấp quyền OWNER.' : action === 'REJECT' ? 'Đã từ chối hồ sơ.' : 'Đã yêu cầu bổ sung hồ sơ.', 'success'); } catch (error) { toast(error instanceof Error ? error.message : 'Không thể xử lý hồ sơ.', 'error'); } finally { setWorking(false); } };
  return <div className="min-h-screen bg-slate-50"><main className="mx-auto max-w-7xl px-4 py-7 sm:px-6"><Link to="/system-admin" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-brand-700"><ArrowLeft size={16} />Dashboard hệ thống</Link><PageHeader title="Quản lý hồ sơ đối tác" description="Kiểm tra thông tin và ảnh giấy tờ riêng tư trước khi quyết định." />
    <form onSubmit={(event) => { event.preventDefault(); void load(); }} className="mb-5 grid gap-3 rounded-card border bg-white p-4 md:grid-cols-[2fr_1fr_1fr_1fr_auto]"><Input value={query} onChange={(event) => setQuery(event.target.value)} leftIcon={<Search size={16} />} placeholder="Tên, email hoặc số điện thoại" /><select value={status} onChange={(event) => setStatus(event.target.value)} className="rounded-lg border border-slate-300 px-3 text-sm"><option value="">Mọi trạng thái</option>{Object.entries(labels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select><Input type="date" value={from} onChange={(event) => setFrom(event.target.value)} title="Từ ngày" /><Input type="date" value={to} onChange={(event) => setTo(event.target.value)} title="Đến ngày" /><Button type="submit">Lọc</Button></form>
    {loading ? <LoadingSkeleton lines={8} /> : items.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{items.map((item) => <article key={item.id} className="rounded-card border bg-white p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-bold">{item.customer_name}</h2><p className="truncate text-sm text-slate-500">{item.customer_email}</p><p className="text-sm text-slate-500">{item.customer_phone || 'Chưa có SĐT'}</p></div><Badge variant={variant(item.status)}>{labels[item.status]}</Badge></div><div className="mt-4 border-t pt-4 text-sm"><b>{show(item.venue.name)}</b><p className="mt-1 line-clamp-2 text-slate-500">{show(item.venue.address)}</p><p className="mt-3 text-xs text-slate-400">{item.submitted_at ? `Gửi ${new Date(item.submitted_at).toLocaleString('vi-VN')}` : 'Chưa gửi xét duyệt'}</p></div><Button className="mt-4 w-full" variant="outline" onClick={() => void openDetail(item)}>Xem chi tiết</Button></article>)}</div> : <EmptyState title="Không có hồ sơ phù hợp" description="Hãy thay đổi bộ lọc hoặc chờ khách hàng gửi hồ sơ." />}
  </main>{selected && <div className="fixed inset-0 z-50 flex justify-end bg-slate-950/50" onMouseDown={close}><aside className="h-full w-full max-w-2xl overflow-y-auto bg-white p-4 pb-28 shadow-2xl sm:p-6" onMouseDown={(event) => event.stopPropagation()}><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase text-brand-700">Hồ sơ #{selected.id}</p><h2 className="text-xl font-black">{selected.customer_name}</h2></div><button onClick={close} className="rounded-lg p-2 hover:bg-slate-100" aria-label="Đóng"><X /></button></div><Badge className="mt-3" variant={variant(selected.status)}>{labels[selected.status]}</Badge><Detail title="Thông tin CUSTOMER" rows={[['Email', selected.customer_email], ['Điện thoại', selected.customer_phone], ['Người đại diện', selected.representative.name], ['Số giấy tờ / CCCD', selected.representative.identity_number]]} /><Detail title="Thông tin cơ sở" rows={[['Tên cơ sở', selected.venue.name], ['Địa chỉ', selected.venue.address], ['Tỉnh/thành', selected.venue.city], ['Quận/huyện', selected.venue.district], ['Điện thoại', selected.venue.phone], ['Môn thể thao', selected.venue.sports], ['Mô tả', selected.venue.description]]} /><Detail title="Tiến trình xét duyệt" rows={[['Ngày gửi', selected.submitted_at ? new Date(selected.submitted_at).toLocaleString('vi-VN') : null], ['Ngày xét duyệt', selected.reviewed_at ? new Date(selected.reviewed_at).toLocaleString('vi-VN') : null], ['Người xét duyệt', selected.reviewed_by]]} />
      <section className="mt-6"><h3 className="border-b pb-2 font-bold">Ảnh giấy tờ / CCCD</h3>{selected.has_document ? documentUrl ? <button className="relative mt-3 block w-full overflow-hidden rounded-xl border bg-slate-50 p-2" onClick={() => setZoom(true)}><img src={documentUrl} alt="Ảnh giấy tờ" className="mx-auto max-h-96 max-w-full object-contain" /><span className="absolute bottom-4 right-4 inline-flex items-center gap-1 rounded-lg bg-slate-950/75 px-3 py-2 text-xs font-semibold text-white"><ZoomIn size={15} />Phóng to</span></button> : <LoadingSkeleton lines={4} /> : <div className="mt-3 rounded-xl bg-red-50 p-4 text-sm text-red-700"><FileImage className="mb-2" />Hồ sơ chưa có ảnh giấy tờ.</div>}</section>
      {(selected.admin_note || selected.rejection_reason) && <div className="mt-5 rounded-xl bg-amber-50 p-4"><b>Ghi chú xét duyệt</b><p className="mt-1 text-sm">{selected.admin_note || selected.rejection_reason}</p></div>}{selected.status === 'WITHDRAWN' && <div className="mt-5 rounded-xl border border-slate-200 bg-slate-50 p-4"><b>Hồ sơ đã được CUSTOMER rút</b><p className="mt-1 text-sm text-slate-600">Ngày rút: {selected.withdrawn_at ? new Date(selected.withdrawn_at).toLocaleString('vi-VN') : '—'}</p>{selected.withdraw_reason && <p className="mt-2 text-sm text-slate-600">Lý do: {selected.withdraw_reason}</p>}<p className="mt-2 text-xs text-slate-500">Hồ sơ được giữ lại để phục vụ lịch sử và không thể xét duyệt.</p></div>}{selected.status === 'PENDING_REVIEW' && <div className="fixed bottom-0 right-0 flex w-full max-w-2xl flex-wrap gap-2 border-t bg-white p-4 shadow-lg"><Button loading={working} disabled={!selected.has_document} onClick={() => void review('APPROVE')}>Duyệt hồ sơ</Button><Button loading={working} variant="outline" onClick={() => void review('REQUEST_MORE_INFO')}>Yêu cầu bổ sung</Button><Button loading={working} variant="danger" onClick={() => void review('REJECT')}>Từ chối</Button></div>}</aside></div>}{zoom && documentUrl && <div className="fixed inset-0 z-[60] grid place-items-center bg-slate-950/90 p-3 sm:p-8" onClick={() => setZoom(false)}><button className="absolute right-4 top-4 rounded-full bg-white p-2" aria-label="Đóng ảnh"><X /></button><img src={documentUrl} alt="Ảnh giấy tờ phóng to" className="max-h-full max-w-full object-contain" /></div>}</div>;
}

function Detail({ title, rows }: { title: string; rows: [string, unknown][] }) { return <section className="mt-6"><h3 className="border-b pb-2 font-bold">{title}</h3><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-[150px_1fr]">{rows.map(([label, value]) => <div className="contents" key={label}><dt className="text-slate-500">{label}</dt><dd className="break-words font-medium">{show(value)}</dd></div>)}</dl></section>; }
