import { AlertTriangle, ArrowLeft, Building2, FileText, Search, ShieldCheck, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Badge, Button, EmptyState, Input, LoadingSkeleton, Modal, PageHeader, SecureApiImage, useToast } from '@/components/common';
import { apiBlob, apiRequest } from '@/services/apiClient';

type Status = 'DRAFT' | 'PENDING_REVIEW' | 'APPROVED' | 'REJECTED' | 'SUSPENDED';
interface Summary { id: number; name: string; location: string; status: Status; owner_name: string; owner_email: string; submitted_at: string | null; document_count: number; image_count: number; rejection_reason: string | null; }
interface Detail extends Summary { description: string; contact_phone: string; contact_email: string; city: string; district: string; sports: string[]; opening_time: string; closing_time: string; owner_phone: string; images: Array<{ id: number; url: string; category: string; original_name: string }>; documents: Array<{ id: number; document_name: string; document_type: string; original_name: string }>; reviews: Array<{ id: number; action: string; from_status: string; to_status: string; note: string; created_at: string }>; }
const labels: Record<Status, string> = { DRAFT: 'Bản nháp', PENDING_REVIEW: 'Chờ xét duyệt', APPROVED: 'Đã duyệt', REJECTED: 'Cần bổ sung', SUSPENDED: 'Tạm ngừng' };
const variant = (value: Status) => value === 'APPROVED' ? 'success' : value === 'REJECTED' || value === 'SUSPENDED' ? 'danger' : value === 'PENDING_REVIEW' ? 'warning' : 'neutral';

export function SystemAdminFacilityApplicationsPage() {
  const [items, setItems] = useState<Summary[]>([]); const [selected, setSelected] = useState<Detail>();
  const [loading, setLoading] = useState(true); const [working, setWorking] = useState(false);
  const [query, setQuery] = useState(''); const [status, setStatus] = useState('PENDING_REVIEW');
  const [decision, setDecision] = useState<'REJECT' | 'SUSPEND'>(); const [reason, setReason] = useState(''); const [error, setError] = useState('');
  const { toast } = useToast();
  const load = async () => { setLoading(true); try { const params = new URLSearchParams(); if (query.trim()) params.set('search', query.trim()); if (status) params.set('status', status); setItems(await apiRequest<Summary[]>('/admin/facility-applications?' + params)); } catch (e) { toast(e instanceof Error ? e.message : 'Không tải được hồ sơ cơ sở.', 'error'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const open = async (item: Summary) => { try { setSelected(await apiRequest<Detail>('/admin/facility-applications/' + item.id)); } catch (e) { toast(e instanceof Error ? e.message : 'Không tải được chi tiết.', 'error'); } };
  const review = async (action: 'APPROVE' | 'REJECT' | 'SUSPEND' | 'RESTORE', note?: string) => {
    if (!selected) return; setWorking(true);
    try { const updated = await apiRequest<Detail>('/admin/facility-applications/' + selected.id + '/review', { method: 'PATCH', body: JSON.stringify({ action, reason: note || null }) }); setSelected(updated); setItems((current) => current.map((item) => item.id === updated.id ? { ...item, status: updated.status, rejection_reason: updated.rejection_reason } : item)); setDecision(undefined); setReason(''); toast(action === 'APPROVE' ? 'Đã duyệt cơ sở.' : action === 'REJECT' ? 'Đã yêu cầu OWNER bổ sung hồ sơ.' : action === 'SUSPEND' ? 'Đã tạm ngừng cơ sở.' : 'Đã khôi phục cơ sở.', 'success'); }
    catch (e) { toast(e instanceof Error ? e.message : 'Không xử lý được hồ sơ.', 'error'); } finally { setWorking(false); }
  };
  const confirm = () => { const value = reason.trim(); if (value.length < 3) return setError('Lý do phải có ít nhất 3 ký tự.'); void review(decision!, value); };
  const openDocument = async (documentId: number) => {
    if (!selected) return;
    try {
      const blob = await apiBlob('/facilities/' + selected.id + '/documents/' + documentId + '/content');
      const url = URL.createObjectURL(blob);
      window.open(url, '_blank', 'noopener,noreferrer');
      window.setTimeout(() => URL.revokeObjectURL(url), 60000);
    } catch (e) { toast(e instanceof Error ? e.message : 'Không mở được tài liệu.', 'error'); }
  };

  return <div className="min-h-screen bg-slate-50"><main className="mx-auto max-w-7xl px-4 py-7 sm:px-6"><Link to="/system-admin" className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-brand-700"><ArrowLeft size={16} />Dashboard hệ thống</Link><PageHeader title="Duyệt cơ sở" description="Kiểm tra thông tin, hình ảnh và tài liệu xác minh trước khi cho phép cơ sở nhận booking." />
    <form className="mb-5 flex flex-col gap-3 rounded-card border bg-white p-4 sm:flex-row" onSubmit={(e) => { e.preventDefault(); void load(); }}><Input className="flex-1" leftIcon={<Search size={16} />} placeholder="Tên cơ sở, OWNER hoặc địa chỉ" value={query} onChange={(e) => setQuery(e.target.value)} /><select className="field sm:w-52" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">Mọi trạng thái</option>{Object.entries(labels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><Button type="submit">Lọc</Button></form>
    {loading ? <LoadingSkeleton lines={8} /> : items.length ? <div className="overflow-x-auto rounded-card border bg-white"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-slate-50"><tr>{['Cơ sở', 'OWNER', 'Địa chỉ', 'Ngày gửi', 'Tài liệu', 'Trạng thái', ''].map((label) => <th className="px-4 py-3" key={label}>{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr className="border-t" key={item.id}><td className="px-4 py-3 font-bold">{item.name}</td><td className="px-4 py-3">{item.owner_name}<small className="block text-slate-500">{item.owner_email}</small></td><td className="px-4 py-3">{item.location}</td><td className="px-4 py-3">{item.submitted_at ? new Date(item.submitted_at).toLocaleString('vi-VN') : '—'}</td><td className="px-4 py-3">{item.document_count} tài liệu · {item.image_count} ảnh</td><td className="px-4 py-3"><Badge variant={variant(item.status)}>{labels[item.status]}</Badge></td><td className="px-4 py-3"><Button size="sm" variant="outline" onClick={() => void open(item)}>Xem chi tiết</Button></td></tr>)}</tbody></table></div> : <EmptyState icon={<Building2 />} title="Không có hồ sơ phù hợp" description="Chưa có cơ sở nào trong trạng thái đã chọn." />}
    </main>
    {selected && <div className="fixed inset-0 z-40 flex justify-end bg-slate-950/50" onMouseDown={() => setSelected(undefined)}><aside className="h-full w-full max-w-3xl overflow-y-auto bg-white p-5 pb-28 shadow-2xl sm:p-7" onMouseDown={(e) => e.stopPropagation()}><div className="flex justify-between"><div><p className="text-xs font-bold uppercase text-brand-700">Hồ sơ cơ sở #{selected.id}</p><h2 className="text-2xl font-black">{selected.name}</h2><Badge className="mt-2" variant={variant(selected.status)}>{labels[selected.status]}</Badge></div><button onClick={() => setSelected(undefined)} aria-label="Đóng"><X /></button></div>
      <Section title="Thông tin OWNER" rows={[['Họ tên', selected.owner_name], ['Email', selected.owner_email], ['Điện thoại', selected.owner_phone]]} /><Section title="Thông tin cơ sở" rows={[['Địa chỉ', selected.location], ['Tỉnh/thành', selected.city], ['Khu vực', selected.district], ['Hotline', selected.contact_phone], ['Email', selected.contact_email], ['Giờ hoạt động', selected.opening_time?.slice(0, 5) + '–' + selected.closing_time?.slice(0, 5)], ['Môn thể thao', selected.sports?.join(', ')], ['Mô tả', selected.description]]} />
      <h3 className="mt-6 border-b pb-2 font-bold">Hình ảnh</h3><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{selected.images.map((image) => <SecureApiImage key={image.id} src={image.url} alt={image.original_name} className="h-32 w-full rounded-xl border object-cover" />)}</div>
      <h3 className="mt-6 border-b pb-2 font-bold">Tài liệu xác minh</h3><div className="mt-3 space-y-2">{selected.documents.map((doc) => <button key={doc.id} type="button" onClick={() => void openDocument(doc.id)} className="flex w-full items-center gap-2 rounded-xl border p-3 text-left text-sm font-semibold text-brand-700 hover:bg-brand-50"><FileText size={17} />{doc.document_name} · {doc.original_name}</button>)}</div>
      <h3 className="mt-6 border-b pb-2 font-bold">Lịch sử xét duyệt</h3><div className="mt-3 space-y-2">{selected.reviews.map((event) => <div key={event.id} className="rounded-xl bg-slate-50 p-3 text-sm"><b>{event.action}</b> · {event.from_status || '—'} → {event.to_status}<small className="block text-slate-500">{new Date(event.created_at).toLocaleString('vi-VN')} {event.note ? '· ' + event.note : ''}</small></div>)}</div>
      <div className="fixed bottom-0 right-0 flex w-full max-w-3xl flex-wrap gap-2 border-t bg-white p-4 shadow-lg">{selected.status === 'PENDING_REVIEW' && <><Button loading={working} leftIcon={<ShieldCheck size={17} />} onClick={() => void review('APPROVE')}>Duyệt cơ sở</Button><Button disabled={working} variant="danger" onClick={() => { setDecision('REJECT'); setReason(''); setError(''); }}>Từ chối / yêu cầu bổ sung</Button></>}{selected.status === 'APPROVED' && <Button variant="danger" onClick={() => setDecision('SUSPEND')}>Tạm ngừng</Button>}{selected.status === 'SUSPENDED' && <Button onClick={() => void review('RESTORE')}>Khôi phục</Button>}</div>
    </aside></div>}
    <Modal open={Boolean(decision)} onClose={() => !working && setDecision(undefined)} title={decision === 'SUSPEND' ? 'Tạm ngừng cơ sở' : 'Từ chối / yêu cầu bổ sung'} description={selected ? selected.name + ' · OWNER ' + selected.owner_name : ''}><div className="rounded-xl bg-amber-50 p-3 text-sm text-amber-900"><AlertTriangle size={17} className="mr-2 inline" />Thao tác này sẽ ngừng hiển thị cơ sở và chặn booking mới.</div><label className="mt-4 block text-sm font-semibold">Lý do<textarea autoFocus maxLength={1000} className={'field mt-2 min-h-28 ' + (error ? 'border-red-400' : '')} placeholder="Nhập lý do rõ ràng để OWNER có thể xử lý..." value={reason} onChange={(e) => { setReason(e.target.value); setError(''); }} /></label>{error && <p className="mt-1 text-xs text-red-600">{error}</p>}<div className="mt-5 flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><Button variant="outline" disabled={working} onClick={() => setDecision(undefined)}>Hủy</Button><Button variant="danger" loading={working} onClick={confirm}>Xác nhận</Button></div></Modal>
  </div>;
}
function Section({ title, rows }: { title: string; rows: [string, unknown][] }) { return <section className="mt-6"><h3 className="border-b pb-2 font-bold">{title}</h3><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-[150px_1fr]">{rows.map(([label, value]) => <div className="contents" key={label}><dt className="text-slate-500">{label}</dt><dd className="break-words font-medium">{value ? String(value) : '—'}</dd></div>)}</dl></section>; }