import { CheckCircle2, Clock3, MapPin, Phone, Star, Users } from 'lucide-react';
import { useState } from 'react';
import type { Venue } from '@/types/index';
import { Badge } from '@/components/common';
import { MapMock } from './MapMock';

const tabs = ['Tổng quan', 'Sân', 'Tiện ích', 'Đánh giá', 'Chính sách'] as const;
type Tab = typeof tabs[number];
export function VenueDetailTabs({ venue }: { venue: Venue }) {
  const [active, setActive] = useState<Tab>('Tổng quan');
  return <section className="overflow-hidden rounded-card border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto border-b border-slate-200"><div className="flex min-w-max px-2">{tabs.map((tab) => <button key={tab} onClick={() => setActive(tab)} className={`border-b-2 px-4 py-4 text-sm font-semibold transition ${active === tab ? 'border-brand-600 text-brand-700' : 'border-transparent text-slate-500 hover:text-slate-800'}`}>{tab}</button>)}</div></div><div className="p-5 sm:p-6">
    {active === 'Tổng quan' && <div className="space-y-7"><div><h2 className="text-xl font-bold text-slate-900">Giới thiệu</h2><p className="mt-3 leading-7 text-slate-600">{venue.description}</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-lg bg-slate-50 p-4"><p className="flex items-center gap-2 text-sm font-bold text-slate-800"><Clock3 size={18} className="text-brand-600" />Giờ hoạt động</p><p className="mt-2 text-sm text-slate-600">{venue.hours}</p></div><div className="rounded-lg bg-slate-50 p-4"><p className="flex items-center gap-2 text-sm font-bold text-slate-800"><MapPin size={18} className="text-sportblue-600" />Địa chỉ</p><p className="mt-2 text-sm text-slate-600">{venue.address}, {venue.city}</p></div><div className="rounded-xl border border-brand-100 bg-brand-50/80 p-4 sm:col-span-2"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="flex items-center gap-2 text-sm font-semibold text-slate-800"><Phone size={18} className="text-brand-700" />Hotline chủ sân / cơ sở</p>{venue.hotline ? <a href={`tel:${venue.hotline.replace(/[^\d+]/g, '')}`} className="ml-7 mt-1 inline-block text-[15px] font-normal text-brand-800 hover:underline">{venue.hotline}</a> : <p className="ml-7 mt-1 text-sm text-slate-600">0901 234 567</p>}<p className="ml-7 mt-1 text-xs text-slate-500">Vui lòng liên hệ trong giờ hoạt động của sân</p></div><a href={`tel:${(venue.hotline || '0901 234 567').replace(/[^\d+]/g, '')}`} className="inline-flex h-9 shrink-0 self-start items-center justify-center gap-1.5 rounded-lg bg-brand-600 px-3 text-xs font-semibold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-brand-700 sm:h-10 sm:self-auto sm:gap-2 sm:rounded-xl sm:px-4 sm:text-sm"><Phone size={15} />Gọi ngay</a></div></div></div><MapMock venues={[venue]} selectedId={venue.id} className="h-80" /></div>}
    {active === 'Sân' && <div><h2 className="text-xl font-bold text-slate-900">Danh sách sân</h2><div className="mt-4 space-y-3">{venue.courts.map((court) => <article key={court.id} className="rounded-lg border border-slate-200 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><div className="flex items-center gap-2"><h3 className="font-bold text-slate-900">{court.name}</h3><Badge variant={court.availableSlots.length ? 'success' : 'neutral'}>{court.availableSlots.length ? 'Có lịch trống' : 'Hết chỗ'}</Badge></div><p className="mt-1 text-sm text-slate-500">{court.type} • {court.surface} • {court.indoor ? 'Trong nhà' : 'Ngoài trời'}</p></div><b className="text-brand-700">{court.price.toLocaleString('vi-VN')}đ/giờ</b></div><div className="mt-3 flex flex-wrap gap-2">{court.availableSlots.map((slot) => <span key={slot} className="rounded-md bg-brand-50 px-2 py-1 text-xs font-semibold text-brand-700">{slot}</span>)}</div></article>)}</div></div>}
    {active === 'Tiện ích' && <div><h2 className="text-xl font-bold text-slate-900">Tiện ích tại cơ sở</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{venue.amenities.map((amenity) => <div key={amenity} className="flex items-center gap-3 rounded-lg bg-slate-50 p-3 text-sm font-medium text-slate-700"><CheckCircle2 size={18} className="text-brand-600" />{amenity}</div>)}</div></div>}
    {active === 'Đánh giá' && <div><div className="flex items-end gap-3"><strong className="text-5xl font-extrabold text-slate-900">{venue.rating}</strong><div><p className="flex text-amber-400">{Array.from({ length: 5 }).map((_, index) => <Star key={index} size={16} className="fill-current" />)}</p><p className="mt-1 text-xs text-slate-500">{venue.reviewCount} đánh giá đã xác minh</p></div></div><div className="mt-6 space-y-4">{[['Minh Khang', 'Sân sạch, mặt sân tốt và nhân viên hỗ trợ rất nhanh.'], ['Hoàng Yến', 'Đặt lịch thuận tiện, phòng thay đồ sạch sẽ.']].map(([name, review]) => <article key={name} className="border-t border-slate-100 pt-4"><p className="flex items-center gap-2 font-semibold text-slate-800"><span className="grid h-8 w-8 place-items-center rounded-full bg-brand-100 text-xs text-brand-700"><Users size={15} /></span>{name}</p><p className="mt-2 text-sm leading-6 text-slate-600">{review}</p></article>)}</div></div>}
    {active === 'Chính sách' && <div><h2 className="text-xl font-bold text-slate-900">Chính sách đặt sân</h2><ul className="mt-4 space-y-3">{venue.policies.map((policy) => <li key={policy} className="flex gap-3 rounded-lg bg-slate-50 p-4 text-sm text-slate-600"><CheckCircle2 size={18} className="shrink-0 text-brand-600" />{policy}</li>)}</ul></div>}
  </div></section>;
}
